### PR TITLE
Html styling

### PR DESCRIPTION
**Pull request by HansOlsson**
Cherry-picked HTML-styling changes from master that improve usability.
(No change of text.)

### CODE REVIEW

**Comment by HansOlsson** [comment]
(Should have been a draft - want to add one more.)

**Comment by henrikt-ma** [comment]
> (Should have been a draft - want to add one more.)

Then you should click "Convert to draft"! :)

**Comment by HansOlsson** [comment]
> > (Should have been a draft - want to add one more.)
> 
> Then you should click "Convert to draft"! :)

Found it, and have now converted back to non-draft as it is ready for review.

**Review by henrikt-ma — APPROVED** [review]
Looks good; that is, it looks like a safe collections of commits to cherry-pick into _maint/3.5_.

**Pull request merged**
