### PR TITLE
Mandate that Axis.unit is used for axis tick labels

### PR DESCRIPTION
**Pull request by henrikt-ma**
When working on #2632 – what it means to not specify `unit` – we got aware that we were also missing the important meaning of _only_ specifying `unit` for an `Axis`.  More generally, the `unit` should serve two independent purposes:
- It is the unit in which to express values showed on the axis tick labels.
- It is the unit used to define the axis boundaries `min` and `max`.

### CODE REVIEW

**Comment by HansOlsson** [comment]
I agree that the change clarifies the current status. But the underlying design is somewhat confusing.
For normal variables this unit corresponds to the displayUnit, and min/max attributes are in Modelica code given in the original SI-unit, not the displayUnit.

**Comment by henrikt-ma** [comment]
> I agree that the change clarifies the current status. But the underlying design is somewhat confusing.
> For normal variables this unit corresponds to the displayUnit, and min/max attributes are in Modelica code given in the original SI-unit, not the displayUnit.

It does correspond to the `unit` of a normal variable, in the sense that the values seen in the `Axis.min` and `Axis.max` (with no need for a GUI to make unit conversions on the fly) are the actual values at the axis boundaries (in the given `unit`).  To have both `Axis.unit` and `Axis.displayUnit` would make things more complicated:
- Tools need to make on-the-fly conversions to allow editing values in a different unit than the unit actually being stored.  Without such tool support, the annotation becomes harder for humans to understand and edit.
- The bounds should be literals, not general expressions, meaning that no implicit unit conversion from variables stored with different `unit` will be needed.  Perhaps this would need clarification?
- The possibility for incompatible `unit` and `displayUnit` would add another source of errors.

**Comment by HansOlsson** [comment]
> > I agree that the change clarifies the current status. But the underlying design is somewhat confusing.
> > For normal variables this unit corresponds to the displayUnit, and min/max attributes are in Modelica code given in the original SI-unit, not the displayUnit.
> 
> It does correspond to the `unit` of a normal variable, in the sense that the values seen in the `Axis.min` and `Axis.max` (with no need for a GUI to make unit conversions on the fly) are the actual values at the axis boundaries (in the given `unit`). To have both `Axis.unit` and `Axis.displayUnit` would make things more complicated:

Yes, but I was more arguing that `Axis.unit` sort of worked like `Axis.displayUnit`; and possibly should be renamed to make that clearer, not that we need both. (The underlying unit should be given based on what is plotted.)

Which unit to give min/max in has additional nuances:
* Changing the unit requires updating min/max even if you want to sort of plot the same "region".
* If the unit-conversion isn't a simple factor of 10 having min/max in the displayUnit would require a back-calculation leading to weird min/max values.
* The unit conversions aren't part of the Modelica standard; whereas they are part of the FMI-standard. That isn't a problem for prefixed SI-units and some common non-SI units - but there are always esoteric cases.

**Thus I would at least propose two additional statements (to be formulated):**
* If a tool finds that the unit is incompatible with what is plotted it is recommend to give a warning, and treat the unit as if it was not specified. (If you try to plot a voltage in "mA".)
* If the unit is not specified (or not recognized) the min/max bounds are ignored, and the tool computes them automatically.

Note: We now have three cases for specified units: compatible with plots, unknown and incompatible.

**Comment by henrikt-ma** [comment]
> Yes, but I was more arguing that `Axis.unit` sort of worked like `Axis.displayUnit`; and possibly should be renamed to make that clearer, not that we need both. (The underlying unit should be given based on what is plotted.)

As long as `min` and `max` are given in `Axis.unit`, I think we should keep the name.  As I see it, `displayUnit` is only for display and convenient editing; not for the underlying values being stored.

> Which unit to give min/max in has additional nuances:
> 
> * Changing the unit requires updating min/max even if you want to sort of plot the same "region".

Yes, but I think it might  be just as common for a human user intending to change `min`, `max` and `unit` all at once, and then it becomes very annoying if one first changes `min` and `max`, and then have the tool messing with these values when finally setting the unit.  Each variant has its clear advantages and disadvantages here; I don't think either variant is clearly better when it comes to editing the values.

> * If the unit-conversion isn't a simple factor of 10 having min/max in the displayUnit would require a back-calculation leading to weird min/max values.

Right, this is kind of one of the arguments I gave above for sticking with `unit`.

> * The unit conversions aren't part of the Modelica standard; whereas they are part of the FMI-standard. That isn't a problem for prefixed SI-units and some common non-SI units - but there are always esoteric cases.

Modelica already has both `unit` and `displayUnit`, meaning that tools need to know how to convert between the two.  I would love to see proper unit handling in Modelica, but I don't see anything in this MCP that requires anything more than we already have.

> **Thus I would at least propose two additional statements (to be formulated):**
> 
> * If a tool finds that the unit is incompatible with what is plotted it is recommend to give a warning, and treat the unit as if it was not specified. (If you try to plot a voltage in "mA".)
> * If the unit is not specified (or not recognized) the min/max bounds are ignored, and the tool computes them automatically.
> 
> Note: We now have three cases for specified units: compatible with plots, unknown and incompatible.

This belongs to #2632, so let's have the discussion there instead!

**Review by DagBruck — COMMENTED** [review]
Seems legit.

**Pull request merged**
