### PR TITLE
Styling cleanup for 'derivative' annotation

### PR DESCRIPTION
**Pull request by henrikt-ma**
I finally found the time to follow up on https://github.com/modelica/ModelicaSpecification/pull/2864#pullrequestreview-596828747 and take the planned look at the styling.

To understand the changes, it's probably best to look at the individual commits.

### CODE REVIEW

**Review by eshmoylova — COMMENTED** [review]
Where are the macros for `\udfrac` and `\pdfrac` defined?

**Comment by HansOlsson** [comment]
> udfrac

Both are in mlsshared.sty - it would be good if we could re-use some existing definitions instead; but for some reason there doesn't seem to be a common variant of it.

**Review by HansOlsson — APPROVED** [review]
Still looks good.

**Comment by henrikt-ma** [comment]
> > Where are the macros for \udfrac and \pdfrac defined?
> 
> Both are in mlsshared.sty - it would be good if we could re-use some existing definitions instead; but for some reason there doesn't seem to be a common variant of it.

Right, it would have been a mistake to introduce the commands in _mlsshared.sty_ if there was a standard way of doing it.

**Pull request merged**
