### PR TITLE
Use the listings.sty option upquote=true

### LINKED ISSUE #3122: Q-Ident limiter in generated HTML
The Q-Ident limiter in the generated HTML looks like a right single quotation mark (= &rsquo; = U+2019), but would be syntactically more correct/consistent if displayed as apostroph (= &apos; = U+0027).

grafik

### PR DESCRIPTION
**Pull request by henrikt-ma**
Fixes #3122.

I expect that this won't work in the CI build because of the added dependency on _textcomp.sty_, and I have yet to figure out how to find my ways around the new license restrictions of Docker…

### CODE REVIEW

**Comment by henrikt-ma** [comment]
@sjoelund, do you know what might be the proper way of fixing this error in the pdfLaTeX build?
```
(https://test.openmodelica.org/jenkins/blue/organizations/jenkins/ModelicaAssociation%2FModelicaSpecification/detail/PR-3123/1/#step-51-log-208)[8] (/usr/local/texlive/texmf-dist/tex/latex/newtxtt/ts1newtxtt.fd)
kpathsea: Running mktextfm tcxtt
/usr/local/texlive/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for tcxtt.
/usr/local/texlive/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input tcxtt
This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

kpathsea: Running mktexmf tcxtt

! I can't find file `tcxtt'.
<*> ...=ljfour; mag:=1; ; nonstopmode; input tcxtt
                                                  
Please type another input file name
! Emergency stop.
<*> ...=ljfour; mag:=1; ; nonstopmode; input tcxtt
                                                  
Transcript written on mfput.log.
grep: tcxtt.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input tcxtt' failed to make tcxtt.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font TS1/newtxtt/m/n/10=tcxtt at 10.0pt not loadable: Metric (TFM) file not f
ound.
```

**Comment by sjoelund** [comment]
I assume the docker image needs the font installed

**Comment by henrikt-ma** [comment]
When I try to make an incremental update of the Docker image I get this error:
```
tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

Are we ready to switch to 2021?

**Comment by HansOlsson** [comment]
> When I try to make an incremental update of the Docker image I get this error:
> 
> ```
> tlmgr: Local TeX Live (2020) is older than remote repository (2021).
> Cross release updates are only supported with
>   update-tlmgr-latest(.sh/.exe) --update
> See https://tug.org/texlive/upgrade.html for details.
> ```
> 
> Are we ready to switch to 2021?

I believe so, I couldn't see anything problematic in https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-880009.2

**Comment by sjoelund** [comment]
It's that or waiting for 2022 (April 3)

**Comment by HansOlsson** [comment]
> It's that or waiting for 2022 (April 3)

I would propose to update now, since I couldn't see any major important changes in https://tug.org/texlive/pretest.html

**Comment by henrikt-ma** [comment]
OK.  What should happen to _Dockerfile.incremental_ and _Dockerfile.2.incremental_ when the image is updated using _Dockerfile_?

**Comment by henrikt-ma** [comment]
My attempts at fixing the _Dockerfile_ have only failed in various ways so far.  I think I might need a bit of help…

Last failure I ran into was this:
```
Cannot determine type of tlpdb from /root/texmf!
cannot setup TLPDB in /root/texmf at /usr/bin/tlmgr line 6424.
```

**Comment by henrikt-ma** [comment]
@sjoelund or @HansOlsson, any ideas for how to update the Docker image?

This is what my current attempt at updating the _Dockerfile_ looks like:
```
diff --git a/.CI/latexml/Dockerfile b/.CI/latexml/Dockerfile
index ea3f642..a2a7e77 100644
--- a/.CI/latexml/Dockerfile
+++ b/.CI/latexml/Dockerfile
@@ -5,12 +5,12 @@ ENV PATH="/usr/local/texlive/bin/x86_64-linux:${PATH}"
 RUN sed -i s,http://archive.ubuntu.com/ubuntu/,mirror://mirrors.ubuntu.com/mirrors.txt, /etc/apt/sources.list \
  && apt-get update \
  && export DEBIAN_FRONTEND=noninteractive \
- && apt-get install -qy perl ca-certificates make libxslt1.1 libxslt-dev libxml2 libxml2-dev gcc wget curl git unzip cpanminus --no-install-recommends --no-install-suggests \
+ && apt-get install -qy perl ca-certificates make libxslt1.1 libxslt-dev libxml2 libxml2-dev gcc wget curl git unzip cpanminus texlive-latex-base --no-install-recommends --no-install-suggests \
  && export PATH="/tmp/texlive/bin/x86_64-linux:$PATH" \
  && REMOTE="http://mirror.ctan.org/systems/texlive/tlnet" \
  && INSTALL="/tmp/install-texlive" \
  && mkdir -p $INSTALL \
- && echo "export PATH=$PATH:/usr/local/texlive/2020/bin" >> /etc/environment \
+ && echo "export PATH=$PATH:/usr/local/texlive/2021/bin" >> /etc/environment \
  && curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL --strip-components=1 \
  && echo selected_scheme scheme-basic > texlive.profile \
  && echo TEXDIR /usr/local/texlive/ >> texlive.profile \
@@ -23,7 +23,7 @@ RUN sed -i s,http://archive.ubuntu.com/ubuntu/,mirror://mirrors.ubuntu.com/mirro
  && $INSTALL/install-tl --profile texlive.profile \
  && rm texlive.profile \
  && tlmgr update --self --all --reinstall-forcibly-removed \
- && tlmgr install latexmk listings caption cleveref xcolor float multirow tocloft parskip etoolbox index biblatex biber newtxtt \
+ && tlmgr install latexmk listings caption cleveref xcolor float multirow tocloft parskip etoolbox index biblatex biber newtxtt texlive-fonts-recommended \
  && cpanm JSON \
  && cpanm LaTeXML \
  && apt-get autoremove -qy make gcc curl wget git cpanminus libxml2-dev libxslt-dev \
```

**Comment by sjoelund** [comment]
I updated the dockerfile with the correct tlmgr name and tested that with tl2021, but I also updated the dockerfile to 2022 as it's going to be released on Sunday anyway and we'll have fewer texlive updates to test for.

**Comment by henrikt-ma** [comment]
> I updated the dockerfile with the correct tlmgr name and tested that with tl2021, but I also updated the dockerfile to 2022 as it's going to be released on Sunday anyway and we'll have fewer texlive updates to test for.

Shouldn't this technically happen directly on _master_ in case this PR gets stuck?

**Comment by sjoelund** [comment]
> Shouldn't this technically happen directly on master in case this PR gets stuck?

Probably :)

**Comment by henrikt-ma** [comment]
Closing and reopening to re-trigger checks.

**Review by HansOlsson — APPROVED** [review]
seems ok

**Pull request merged**
