### PR TITLE
Treat 'connect' like the keyword it is in listings

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]
Ok, makes sense.

**Review by HansOlsson — COMMENTED** [review]
I'm not sure this is ideal. To me `connect `(and `der`) are more "functions" than normal keywords and thus I think I prefer the current highlighting of both of them.

**Review by HansOlsson — CHANGES_REQUESTED** [review]
As indicated I would need more time to consider this.

**Comment by henrikt-ma** [comment]
Right, this shouldn't be fixed for just `connect`:
- Keywords with deviating color: `connect`, `der` (very obvious in list of keywords: https://specification.modelica.org/master/lexical-structure.html#modelica-keywords)
- Non-keywords colored as "keywords": `assert`, `initialState`, `nondiscrete`, `size`, `terminate`, `transition`

Having more than one color for different categories of keywords sounds like a good idea, if we can only come up with enough colors that also work well in inline listings.  One of the challenges I see here is the coloring of `initial` vs `initial equation` and `initial algorithm` – I find it hard to think of a categorization that wouldn't put these in different categories, and it remains to be seen whether _listings.sty_ can handle two word combinations…

The real problem I'd like to address with this PR is that there are colors that are used by both keywords and non-keywords.  I find it impossible to argue that readers understand that coloring has nothing to do with keyword status.

**Comment by HansOlsson** [comment]
Proposal: connect and der same color as non-keywords as assert, but bold-face.

**Comment by henrikt-ma** [comment]
Small update regarding work in progress: The fonts currently used for the pdfLaTeX build doesn't distinguish between medium weight and boldface, which is a bit of a regression from the 3.4 document, and meaning that the discussion in this issue so far has been partly hypothetical (there is a different in font weight in the LaTeXML build).  Because of this, I'm currently trying to find a better source code font for the pdfLaTeX build.  Once I've found something, I plan to switch the font as part of this PR, so that the choice of font can be discussed together with how different font weights are used for syntax highlighting.

**Comment by henrikt-ma** [comment]
I am a aware of the CI failure, and it should be fixed within the next few days.  That aside, I consider this ready for another round of feedback.

**Review by HansOlsson — APPROVED** [review]
Ok, I think it is ok now.

**Pull request merged**
