### PR TITLE
Design98

### PR DESCRIPTION
**Pull request by HansOlsson**
The following was discussed at the 98th design meeting:

- [x] Color for functions/operators? One possibility is to only use special color for special operators: delay, homotopy, ... (but not sin, cos, ...).
- [x] Change footnotesize to small in main document
- [x] Change subsection -> section for autoref
- [x] Define newenvironment "nonnormative", well, it became command.
- [x] Use parskip and no indent.

In addition Henrik thought the link for MCP/0031 should be more direct.
@tbeu I don't know if something special is needed for parskip-package.

### CODE REVIEW

**Comment by HansOlsson** [comment]
@sjoelund can you figure out what is wrong with Jenkins for this? 
I had to add parbox and etoolbox for travis.

**Comment by beutlich** [comment]
If we resolve #2317 first by removing the Travis builds this should be a non-issue then.

**Comment by HansOlsson** [comment]
> If we resolve #2317 first by removing the Travis builds this should be a non-issue then.
> @HansOlsson Just give your OK and I'll do.

As I understand it Travis generates the actual documens, so that is OK!

**Comment by sjoelund** [comment]
Well, you need to update the Jenkinsfile and generate a new texlive installation if you add new packages :)

**Comment by beutlich** [comment]
> Well, you need to update the Jenkinsfile and generate a new texlive installation if you add new packages :)

Can you please do? Thanks.

> As I understand it Travis generates the actual documens, so that is OK!

Ah, sorry. Travis CI was working, but Jenkins failed.

**Pull request merged**
