### PR TITLE
Don't allow language version comment anywhere except at top level

### PR DESCRIPTION
**Pull request by henrikt-ma**
At the 100th design meeting, @HansOlsson wanted us to rethink the earlier decision to allow language version to be specified at different levels of a package hierarchy.  The purpose of this PR is to invite for discussion of this topic, so that we can settle it (again) at the next design meeting.

### CODE REVIEW

**Comment by HansOlsson** [comment]
To clarify: my main concern is with mixing language versions (and specifying language versions in different places allows/encourages this).

Basically allowing different versions will allow us to have component of a model from one language used in a model of another language version, and it will require carrying around information about which rules to use for each element - and it is not even clear that it is possible in all cases.
It also seems to require substantial testing and we already lack tests in ModelicaCompliance.

If we consider a large library where some parts are not really maintained, it should still be fairly simple to upgrade those parts to the new Modelica semantics without knowledge of the domain - e.g. renaming components to avoid collision with a new keyword or changing %par to %{par}.

**Comment by dietmarw** [comment]
I seem to remember that there was also the notion of having the version of the language **outside** the language file in a kind of "config" file. That same file could then also be used for all the library dependencies and other information important for the management of libraries. I think @mtiller presented the arguments but I can't recall the ticket. So basically similar to the (Dymola specific?) library.mos. But it should be in a standard format like json that can be parsed without having to have knowledge of the Modelica version to expect. 

So would it not be an idea to revisit that idea at the same time? If not feel free to ignore this comment.

**Comment by mtiller** [comment]
IIRC, my concerns wasn't with having the language version outside the file, it was with having the dependencies outside the file.  The current system requires that an external package manager has to parse the Modelica annotations in order to extract dependency information.

**Comment by HansOlsson** [comment]
Poll for merging (only at top change to branch):
Favor: 9
Against: 0
Abstain: 0

**Pull request merged**
