### PR TITLE
Table fine

### LINKED ISSUE #3156: Broken tables in HTML master
It seems some tables are broken in the HTML-rendering of master, for example the inheritance table in [7.1.3](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#restrictions-on-the-kind-of-base-class) (note how `expandable connector` incorrectly spans several columns):
inheritance_table
Other tables with similar issues are e.g. the operator precedence table in [3.2](https://specification.modelica.org/master/operators-and-expressions.html#operator-precedence-and-associativity) and many tables in [10](https://specification.modelica.org/master/arrays.html) where entire columns are missing text.

I get the same issue in both Firefox and Chrome, and the missing text is actually missing in the HTML source code so it's not just a browser rendering issue. The PDF is fine though, as is the HTML for older versions of the specification.

### LINKED ISSUE #3158: SEMLA: update to RESTful API
Maybe it is just the latest fad, but many contemporary web applications are built on what is commonly called a REST API (https://en.wikipedia.org/wiki/Representational_state_transfer). I'm not really an expert, but it seems to me that the biggest impact is on the implementation of the server-side software, but there there is indirectly an impact on the client API as well. Typically, we have an API based on very simple, state-less, HTTPS requests such as GET, POST, etc.

The idea I want to float is this: should we take the current SEMLA proposal one step futher and specify a RESTful API?

### PR DESCRIPTION
**Pull request by HansOlsson**
Cleaned up
And fixes #3205 mistakes
Closes #3156

### CODE REVIEW

**Comment by henrikt-ma** [comment]
Can you explain the relation to #3158?

**Comment by HansOlsson** [comment]
> Can you explain the relation to #3158?

Spelling error!

**Comment by HansOlsson** [comment]
> > Can you explain the relation to #3158?
> 
> Spelling error!

It should be #3156

**Review by henrikt-ma — APPROVED** [review]
Yeah, we should fine someone for forcing us to do this. :)

Looking forward to reverting this once the LaTeXML issue has been fixed!

**Pull request merged**
