### PR TITLE
Add files for editing files using Sublime Text

### PR DESCRIPTION
**Pull request by henrikt-ma**
Could we please add these small files in this non-intrusive location to make editing files using Sublime Text more convenient?

### CODE REVIEW

**Comment by HansOlsson** [comment]
I would prefer if someone who actually uses Sublime looked at this, @dietmarw @sjoelund ?

**Comment by dietmarw** [comment]
Sorry, it's all emacs for me.

**Comment by sjoelund** [comment]
I don't use sublime either, but the files look OK I guess? The only odd one is:
```
    "TEXroot": "../../MLS.tex"
```
But I guess that's because the config-file is 2 levels deep.

Does sublime like to automatically edit this file, and forcing you to commit odd stuff to the repo?

**Comment by henrikt-ma** [comment]
> But I guess that's because the config-file is 2 levels deep.

This part is actually not functional at the moment; seems to be a bug in the LaTeXTools plugin.

> Does sublime like to automatically edit this file, and forcing you to commit odd stuff to the repo?

No, not at all.

**Comment by HansOlsson** [comment]
> > But I guess that's because the config-file is 2 levels deep.
> 
> This part is actually not functional at the moment; seems to be a bug in the LaTeXTools plugin.

Might be best to not add it then, so that no-one expects that it will work.

**Comment by henrikt-ma** [comment]
> > > But I guess that's because the config-file is 2 levels deep.
> > 
> > 
> > This part is actually not functional at the moment; seems to be a bug in the LaTeXTools plugin.
> 
> Might be best to not add it then, so that no-one expects that it will work.

OK, I commented it out, leaving a hint to anyone who gets the idea of trying to use this LaTeXTools feature.  (LaTeXTools seems to assume that the project configuration file is in the same directory as the main LaTeX source, but I didn't want to introduce a habit of putting configuration files for various editors in the project root directory.)

**Comment by henrikt-ma** [comment]
> > > > But I guess that's because the config-file is 2 levels deep.
> > > 
> > > 
> > > This part is actually not functional at the moment; seems to be a bug in the LaTeXTools plugin.
> > 
> > 
> > Might be best to not add it then, so that no-one expects that it will work.
> 
> OK, I commented it out, leaving a hint to anyone who gets the idea of trying to use this LaTeXTools feature. (LaTeXTools seems to assume that the project configuration file is in the same directory as the main LaTeX source, but I didn't want to introduce a habit of putting configuration files for various editors in the project root directory.)

As I was preparing a LaTeXTools bug report for this, I instead ended up finding that it is working as expected on the machine I'm using now.  This machine is overall more up to date than the machine where I first found it to not work, so I think the first (bad) experience can be ignored, and I've re-enabled the setting accordingly.

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Makes sense; except that I don't understand the following lines:
`modelica-dae-representation/derivation-of-stream-equations`
`the-modelica-standard-library/glossary`
`the-modelica-standard-library/glossary/modelica-concrete-syntax`
It seems as if there is some unintended hierarchy.

**Comment by henrikt-ma** [comment]
> Makes sense; except that I don't understand the following lines:
> `modelica-dae-representation/derivation-of-stream-equations`
> `the-modelica-standard-library/glossary`
> `the-modelica-standard-library/glossary/modelica-concrete-syntax`
> It seems as if there is some unintended hierarchy.

Hmm… Has something changed to how the HTML is built?  None of the chapter-related directories are present in my current clone, even after just having rebuilt _MLS.html_.  Seems I would be fine removing them all from `folder_exclude_patterns` (and just remove these old directories from any clone)?  That would leave just the _css_ directory.

I suppose it could make sense to also exclude the _media_ directory, as there are no files there that should be edited using a text editor anyway.

**Comment by HansOlsson** [comment]
> > Makes sense; except that I don't understand the following lines:
> > `modelica-dae-representation/derivation-of-stream-equations`
> > `the-modelica-standard-library/glossary`
> > `the-modelica-standard-library/glossary/modelica-concrete-syntax`
> > It seems as if there is some unintended hierarchy.
> 
> Hmm… Has something changed to how the HTML is built? 

I don't recall that we ever intentionally created such directories.
However, it may have been that in case of some error such directories appeared.

>None of the chapter-related directories are present in my current clone, even after just having rebuilt _MLS.html_. Seems I would be fine removing them all from `folder_exclude_patterns` (and just remove these old directories from any clone)? That would leave just the _css_ directory.

Please do.

> I suppose it could make sense to also exclude the _media_ directory, as there are no files there that should be edited using a text editor anyway.

Text editing of SVG-files?

**Review by HansOlsson — APPROVED** [review]

**Comment by henrikt-ma** [comment]
> > I suppose it could make sense to also exclude the _media_ directory, as there are no files there that should be edited using a text editor anyway.
> 
> Text editing of SVG-files?

Currently, none of the SVG files is the source of any image; just like the PDFs, they should rather be considered build products, and they should be generated together with the corresponding PDFs to ensure consistency between the SVG and PDF variants of the same image.

**Comment by henrikt-ma** [comment]
> > None of the chapter-related directories are present in my current clone, even after just having rebuilt _MLS.html_. Seems I would be fine removing them all from `folder_exclude_patterns` (and just remove these old directories from any clone)? That would leave just the _css_ directory.
> 
> Please do.

Done.

By the way, I am intrigued by the amount of interest there is in a Sublime Text project file.  I have no problem with this file being scrutinized, even if I'd be the only person using it, but it makes me wonder if it Is everybody's secret dream to switch over to Sublime Text?  If it isn't, I think it would make sense for other persons to supply similar project configurations for other editors, so that there is a wide selection of editors that can be used conveniently for making contributions.

**Comment by henrikt-ma** [comment]
> > > I suppose it could make sense to also exclude the _media_ directory, as there are no files there that should be edited using a text editor anyway.
> > 
> > 
> > Text editing of SVG-files?
> 
> Currently, none of the SVG files is the source of any image; just like the PDFs, they should rather be considered build products, and they should be generated together with the corresponding PDFs to ensure consistency between the SVG and PDF variants of the same image.

Note that one of the desirable effects of excluding the SVG files is that careless multi-file search/replace operations without filename globbing would skip the SVG files, which could help avoid accidental changes that might look OK on first glance, but that should really have been made by re-generating the entire SVG along with its PDF sibling instead.

**Review by HansOlsson — APPROVED** [review]
Looks good now.

**Pull request merged**
