### PR TITLE
Use standard mechanisms for bibliography

### PR DESCRIPTION
**Pull request by henrikt-ma**
Good reasons to use a standard mechanism include:
- References in the text become linked to their entry in the bibliography.
- The bibliography gets back-references to the text.
- Consistent but flexible styling of citations and bibliography.

Currently not ready for review, since there are problems with the LaTeXML build.

### CODE REVIEW

**Comment by henrikt-ma** [comment]
Noting that Jenkins doesn't have _biblatex.sty_.  Working on it…

**Comment by sjoelund** [comment]
I could update the image with the packages if needed. I assume you need tlmgr to install biblatex, biber, and some templates?

**Comment by henrikt-ma** [comment]
> I could update the image with the packages if needed. I assume you need tlmgr to install biblatex, biber, and some templates?

Yeah, that would be great!  I am just aware of biblatex and biber, but maybe there are also templates that I'm not aware of.

**Comment by henrikt-ma** [comment]
> > I could update the image with the packages if needed. I assume you need tlmgr to install biblatex, biber, and some templates?
> 
> Yeah, that would be great! I am just aware of biblatex and biber, but maybe there are also templates that I'm not aware of.

Maybe you could also prepare for #2726 by adding _index.sty_ (I hope that the present PR can be merged well in advance of #2726 being ready for review)?

**Comment by henrikt-ma** [comment]
@sjoelund, this now fails at _Verifying symbolic links work_.  This happens quite often, and I don't understand how to deal with it.  Do you have any ideas what could be wrong?

**Comment by HansOlsson** [comment]
> @sjoelund, this now fails at _Verifying symbolic links work_. This happens quite often, and I don't understand how to deal with it. Do you have any ideas what could be wrong?

There are two possibilities for it failing:

- We didn't generate the chapters. Not an issue here.
- Some chapters have been renamed, in this case "literature" was renamed to "bib" - and thus soft linking to "literature.html" failed.

**Comment by sjoelund** [comment]
Yeah, it says A6.html is invalid, and that was renamed to bib.html. So change that link so old URLs are redirected to the new location. It might not hurt to redirect literature.html to bib.html as well :)

**Comment by HansOlsson** [comment]
I also find that naming the chapter "literature" (or possibly "bibliography" - which is a bit more work) is preferable to "bib.html".

**Comment by henrikt-ma** [comment]
> I also find that naming the chapter "literature" (or possibly "bibliography" - which is a bit more work) is preferable to "bib.html".

I'll see what can be done – I didn't actively choose the name _bib.html_.

**Comment by henrikt-ma** [comment]
> Yeah, it says A6.html is invalid, and that was renamed to bib.html. So change that link so old URLs are redirected to the new location. It might not hurt to redirect literature.html to bib.html as well :)

Thanks, now it works.

**Comment by henrikt-ma** [comment]
> > I also find that naming the chapter "literature" (or possibly "bibliography" - which is a bit more work) is preferable to "bib.html".
> 
> I'll see what can be done – I didn't actively choose the name _bib.html_.

I think it looks like it would require too much non-standard processing.  If there was a direct way of telling latexmlpost to use a different name, I agree it would make sense to take the opportunity, but short of that that the cost in terms of maintaining a non-standard build procedure seems to exceed the added value.

**Comment by henrikt-ma** [comment]
I noted this problem with the navbar, but I wouldn't consider it critical:
https://github.com/brucemiller/LaTeXML/issues/1401

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Looks good in general, but:

- In combination with toned-down links it is not obvious that you should click on the _year_ in the entry to get to the bibliography. Would it be possible to turn the entire entry into a link? 

- One entry is missing, found in the footnote:

For the precise definition of structurally inconsistent see the article: Pantelides C.C.: The Consistent Initialization of Differential-Algebraic Systems, SIAM J. Sci. and Stat. Comput. Volume 9, Issue 2, pp. 213–231 (March 1988)

In addition the appendices contain some entries, but I don't think we should add them.

**Comment by sjoelund** [comment]
> Would it be possible to turn the entire entry into a link?

There are some links [here](https://tex.stackexchange.com/questions/247752/hyperlink-the-whole-citation-call-out-not-only-the-year?noredirect=1&lq=1), but I don't think it's worth the trouble. Switching to bibtex likely also works, but it's ancient and doesn't know what the Internet is :)

**Comment by henrikt-ma** [comment]
> > Would it be possible to turn the entire entry into a link?
> 
> There are some links [here](https://tex.stackexchange.com/questions/247752/hyperlink-the-whole-citation-call-out-not-only-the-year?noredirect=1&lq=1), but I don't think it's worth the trouble. Switching to bibtex likely also works, but it's ancient and doesn't know what the Internet is :)

I agree that it would be nice, but that implementing a non-trivial workaround seems like the wrong approach for us.  I'm quite  surprised/disappointed that biblatex doesn't do this, but hoping there is enough pressure from the LaTeX community that we just can sit back and wait.

**Comment by henrikt-ma** [comment]
> * One entry is missing, found in the footnote:
> 
> For the precise definition of structurally inconsistent see the article: Pantelides C.C.: The Consistent Initialization of Differential-Algebraic Systems, SIAM J. Sci. and Stat. Comput. Volume 9, Issue 2, pp. 213–231 (March 1988)

Good one!  Fixed.

> In addition the appendices contain some entries, but I don't think we should add them.

I don't see why not?

**Comment by HansOlsson** [comment]
> > In addition the appendices contain some entries, but I don't think we should add them.
> 
> I don't see why not?

It didn't feel natural, but I had to think to figure out why.
I see reasons against: 
- I generally find that updating the revision-text is odd.
- The bibliography will have too many of our "own" entries, which doesn't look nice.
- Which entries were added seems sort of random.
- I would prefer if the revisions were moved out of the main document at some point (I know that they will disappear then as well), because:
  - With a proper versioning system (like git) we don't need it.
  - It takes too much time to update it.

If the revisions had been a living rationale for the decisions it would have made sense, but I think that should be separate and more structured.

**Comment by henrikt-ma** [comment]
> It didn't feel natural, but I had to think to figure out why.
> I see reasons against:
> 
> * I generally find that updating the revision-text is odd.
> * The bibliography will have too many of our "own" entries, which doesn't look nice.

True.

> * Which entries were added seems sort of random.

I don't know about this one, but I trust you.

> * I would prefer if the revisions were moved out of the main document at some point (I know that they will disappear then as well), because:
>   
>   * With a proper versioning system (like git) we don't need it.
>   * It takes too much time to update it.
> 
> If the revisions had been a living rationale for the decisions it would have made sense, but I think that should be separate and more structured.

Sounds like a plan!

**Review by HansOlsson — APPROVED** [review]
Looks ok now. Hoping that we get better hyperlinks in the future.

**Pull request merged**
