### PR TITLE
Add newtxtt.sty to LaTeXML continuous integration builds

### PR DESCRIPTION
**Pull request by henrikt-ma**
Needed for CI build of #2785.

### CODE REVIEW

**Comment by sjoelund** [comment]
Is the following intended for connect and der?

Screenshot_20210330_093657

**Comment by henrikt-ma** [comment]
> Is the following intended for connect and der?

That is the topic of #2785.

**Review by sjoelund — APPROVED** [review]
Looks OK, but I think the keywords list could use some other language definitions where connect and der were printed as keywords that are not operators. When will latexml support minted so we could have a better syntax highlighting? :)

**Comment by HansOlsson** [comment]
> Looks OK, but I think the keywords list could use some other language definitions where connect and der were printed as keywords that are not operators. When will latexml support minted so we could have a better syntax highlighting? :)

Or have a language dialect for that list and possibly for Partial Derivatives of Function.

**Comment by henrikt-ma** [comment]
It needs to be seen in the light of #2785, which now builds thanks to this PR:
pr-2785-keywords

**Pull request merged**
