### PR TITLE
Remove "extends FilledShape" from Text-definitions.

### PR DESCRIPTION
**Pull request by HansOlsson**
Closes# 2157
It has been deprecated for quite some time, and my proposal is that we either do it now or just after releasing 3.6.

### CODE REVIEW

**Comment by HansOlsson** [comment]
Closes #2157

**Review by henrikt-ma — COMMENTED** [review]
It's difficult for me to asses how much `lineColor` is still in use despite the deprecation, or whether tools actually take any action to make modelers replace `lineColor` by `textColor` in their graphics.  All I can tell right away is that System Modeler will use `textColor` whenever a `Text` is modified using the graphical user interface.

That said, I am generally in favor of removing things that have been deprecated for a while.

**Comment by HansOlsson** [comment]
Phone meeting: No point delaying.

**Review by henrikt-ma — APPROVED** [review]
Looks OK and in agreement with phone meeting decision in https://github.com/modelica/ModelicaSpecification/pull/3316#issuecomment-1351558802.

**Pull request merged**
