### PR TITLE
Fix issue and generalize links in text markup

### PR DESCRIPTION
**Pull request by henrikt-ma**
This is the second of two smaller issues detected in MCP-0031, which is currently in the stage _Under evaluation_.  It is our belief that the MCP is still is sufficiently good shape to proceed with the voting for its acceptance, but that — if the MCP is accepted — we should try to address these issues before the release of the next version of the Modelica Specification.

This PR builds upon the resolution of the first of the two smaller issues, #2691, and improves the specification of links in text markup:
- Fixes an issue where a `variable:` or `plot:` link could be ambiguously interpreted as a normal (relative) URI link.
- Introduces _vendor-specific links_ using a vendor-specific form of URI.

At Wolfram, we have noticed that there are some aspects of our tool-specific features that we can't take full advantage of with vendor-specific annotations alone, as they have a very natural role to play also inside captions.  This is one reason why we want to introduce the vendor-specific links in this PR.  Another reason, as explained in the proposed wording, is that vendor-specific links can be useful for prototyping things that can later become standardized markup.

### CODE REVIEW

**Comment by henrikt-ma** [comment]
Note that an underscore is not allowed in the _nameOfVendor_ part of a vendor-specific link, which means that there is no counterpart to the `__nameOfVendor_shadow` example of a vendor-specific annotation.  This assumes that the link analogy can be handled sufficiently well using something like a URI query instead.

**Review by maltelenz — APPROVED** [review]
One could discuss if this should mirror the vendor annotations by also allowing `__nameOfVendor_something`. As @henrikt-ma mentioned, one can place the `something` in other places in the URI, like the query, or in the `path`. On the other hand, it could be useful to not have to come up with such workarounds.

I don't have strong opinions, so I'm choosing Approve, but would be interested in other peoples opinions/reasoning.

**Comment by otronarp** [comment]
> One could discuss if this should mirror the vendor annotations by also allowing `__nameOfVendor_something`. As @henrikt-ma mentioned, one can place the `something` in other places in the URI, like the query, or in the `path`. On the other hand, it could be useful to not have to come up with such workarounds.

I like the simplicity it offers in terms of specification, with the current proposal of requiring `nameOfVendor` being a valid scheme. 

Also, in my opinion it's a better fit for how schemes are used in general where the scheme usually denotes how you access the resource and then if feels natural with one scheme per tool and that you put the rest in the resource location part of the URI.

**Comment by henrikt-ma** [comment]
> > One could discuss if this should mirror the vendor annotations by also allowing `__nameOfVendor_something`. As @henrikt-ma mentioned, one can place the `something` in other places in the URI, like the query, or in the `path`. On the other hand, it could be useful to not have to come up with such workarounds.
> 
> I like the simplicity it offers in terms of specification, with the current proposal of requiring `nameOfVendor` being a valid scheme.

It's simple, but on the other hand, the more simple it is, the more will it interfere with normal URIs, where the pseudo-scheme will actually be interpreted as the first segment of a relative path.  In view of this, perhaps having only `__nameOfVendor_vendorLinkType` would be an even better solution.  Before sending the whole URI to ones favorite URI parser, one should change it to a valid scheme anyway, but it could be just `dummy:` regardless of what we decide to be the start of a vendor-specific URI.

> Also, in my opinion it's a better fit for how schemes are used in general where the scheme usually denotes how you access the resource and then if feels natural with one scheme per tool and that you put the rest in the resource location part of the URI.

Yes, but only as long as every vendor is fine with having just a single scheme for all its needs.

I think it is also relevant to prepare an answer to the question (possibly for inclusion an non-normative text) what there are the two different forms of vendor-specific annotations, but only one form of vendor-specific URI.  Just as a vendor could be forced into using a single vendor-specific URI scheme, it would have been possible to force the vendor to only use vendor-specific annotations in the nested form, right?

**Comment by otronarp** [comment]
> > > One could discuss if this should mirror the vendor annotations by also allowing `__nameOfVendor_something`. As @henrikt-ma mentioned, one can place the `something` in other places in the URI, like the query, or in the `path`. On the other hand, it could be useful to not have to come up with such workarounds.
> > 
> > 
> > I like the simplicity it offers in terms of specification, with the current proposal of requiring `nameOfVendor` being a valid scheme.
> 
> It's simple, but on the other hand, the more simple it is, the more will it interfere with normal URIs, where the pseudo-scheme will actually be interpreted as the first segment of a relative path. In view of this, perhaps having only `__nameOfVendor_vendorLinkType` would be an even better solution. 

How can it be misinterpreted and how does allowing `_` solves that? The scheme is mandatory so if you don't throw away the leading `__` it's not a valid URI. When you strip the leading `__` you have valid scheme so there is no risk for misinterpretation.


> 
> > Also, in my opinion it's a better fit for how schemes are used in general where the scheme usually denotes how you access the resource and then if feels natural with one scheme per tool and that you put the rest in the resource location part of the URI.
> 
> Yes, but only as long as every vendor is fine with having just a single scheme for all its needs.

They can still have multiple schemes `__ACMESubA` and `__ACMESubB`, they can just not use `_` as separator.

> I think it is also relevant to prepare an answer to the question (possibly for inclusion an non-normative text) what there are the two different forms of vendor-specific annotations, but only one form of vendor-specific URI. Just as a vendor could be forced into using a single vendor-specific URI scheme, it would have been possible to force the vendor to only use vendor-specific annotations in the nested form, right?

What is the purpose of this, introduce annotations in captions or to have vendor specific links in captions?

All I want is a way to mark a link as this is tool specific so if you don't know what to do with it don't try to send it to the system. Also, if you don't know how to interpret it, there shall always be a mandatory alternative text to present. If we want annotations, we should specify annotations instead of URIs. 

So if we want to stick with URIs, perhaps it's better to always require valid URIs and add markup that says that if a tool doesn't recognise the scheme don't make it a link and this is an alternative text that you should show if the link text is missing. Something like:
`%[optional-link-text](URI|mandatory-alternative-text-if-link-text-is-missing)`
And to take the duration example from the PR:
`%(acme:?duration|10 s)`
or with a link text
`%[duration](acme:?duration|)`

**Comment by henrikt-ma** [comment]
> > > > One could discuss if this should mirror the vendor annotations by also allowing `__nameOfVendor_something`. As @henrikt-ma mentioned, one can place the `something` in other places in the URI, like the query, or in the `path`. On the other hand, it could be useful to not have to come up with such workarounds.
> > > 
> > > 
> > > I like the simplicity it offers in terms of specification, with the current proposal of requiring `nameOfVendor` being a valid scheme.
> > 
> > 
> > It's simple, but on the other hand, the more simple it is, the more will it interfere with normal URIs, where the pseudo-scheme will actually be interpreted as the first segment of a relative path. In view of this, perhaps having only `__nameOfVendor_vendorLinkType` would be an even better solution.
> 
> How can it be misinterpreted and how does allowing `_` solves that? The scheme is mandatory so if you don't throw away the leading `__` it's not a valid URI. When you strip the leading `__` you have valid scheme so there is no risk for misinterpretation.

Oh, I somehow thought that we also had "relative URIs" in mind, but I suppose we haven't until that is clearly stated.  I may have been experimenting too much with utilities like this one, which understands that `__Wolfram_foo:bar` doesn't have a scheme:
- https://www.freeformatter.com/url-parser-query-string-splitter.html

I have also studied these examples quite a lot, where most actually don't specify a protocol:
- https://tools.ietf.org/html/rfc3986#section-5.4

Reading it more carefully, I don't see the term _relative URI_; instead they speak of a _URI reference_ and _relative reference_:
> URI-reference is used to denote the most common usage of a resource identifier.
>      URI-reference = URI / relative-ref

Here (from section 1.2):
> A relative reference (Section 4.2) refers to a resource by describing the difference within a hierarchical name space between the reference context and the target URI.

This is something I thought was going to be really useful for linking to plots (and possibly other objects) within a figure in the future.

I also found this in section 1.2:
> NOTE: Previous specifications used the terms "partial URI" and "relative URI" to denote a relative reference to a URI.  As some readers misunderstood those terms to mean that relative URIs are a subset of URIs rather than a method of referencing URIs, this specification simply refers to them as relative references.

Now I wonder: Is it by intention that we've been speaking of _URI_ rather than _URI reference_?

**Comment by henrikt-ma** [comment]
> > > Also, in my opinion it's a better fit for how schemes are used in general where the scheme usually denotes how you access the resource and then if feels natural with one scheme per tool and that you put the rest in the resource location part of the URI.
> > 
> > 
> > Yes, but only as long as every vendor is fine with having just a single scheme for all its needs.
> 
> They can still have multiple schemes `__ACMESubA` and `__ACMESubB`, they can just not use `_` as separator.

It might be subject to debate whether that fulfills the policy:
> … conveying the name of the vendor defining the meaning of the link

Not that it matters much, but I somehow thought that it could be nice if each vendor would take responsibility for a single `nameOfVendor` substring.  If there is a new kid on the block, and you find a link in the MSL with `__NewKid_OnTheBlock`, then you can easily tell that the vendor to chase (for putting vendor-specific links in the MSL) is _NewKid_.  I agree though, that it all sounds vey hypothetical.

**Comment by henrikt-ma** [comment]
> > I think it is also relevant to prepare an answer to the question (possibly for inclusion an non-normative text) what there are the two different forms of vendor-specific annotations, but only one form of vendor-specific URI. Just as a vendor could be forced into using a single vendor-specific URI scheme, it would have been possible to force the vendor to only use vendor-specific annotations in the nested form, right?
> 
> What is the purpose of this, introduce annotations in captions or to have vendor specific links in captions?

No, not to have annotations in captions.  I'm speaking of drawing parallels between the design of vendor-specific annotations and the design of vendor-specific links.  They just seem to have a lot in common, so any lack of symmetry looks a bit odd to me.

> All I want is a way to mark a link as this is tool specific so if you don't know what to do with it don't try to send it to the system. Also, if you don't know how to interpret it, there shall always be a mandatory alternative text to present. If we want annotations, we should specify annotations instead of URIs.

Sure, and for vendor-specific annotations I'm not aware of anything we would need in addition to what is already possible.  At the same time, I think of the vendor-specific links as the text markup analog of what vendor-specific annotations is to annotations in general.  That they aren't required to actually link to anything (the meaning is entirely up to the vendor) could be a little bit confusing, but they surely can link to something, and the form of a link appears to have precisely the structure we need: a replacement for other tools to use, and a syntax which both allows general data to be encoded and allows other tools to easily determine the end of the vendor-specific content.

**Comment by henrikt-ma** [comment]
> So if we want to stick with URIs, perhaps it's better to always require valid URIs and add markup that says that if a tool doesn't recognise the scheme don't make it a link and this is an alternative text that you should show if the link text is missing. 

That wouldn't work with the intention of supporting _lesser known schemes_.  For example, a user with an installation of System Modeler could use links with the `wsm` scheme, expecting other tools to send these to the operating system for interpretation.  I suppose users could find this useful also for schemes that no Modelica tool is aware of.

**Comment by otronarp** [comment]
> > > > > One could discuss if this should mirror the vendor annotations by also allowing `__nameOfVendor_something`. As @henrikt-ma mentioned, one can place the `something` in other places in the URI, like the query, or in the `path`. On the other hand, it could be useful to not have to come up with such workarounds.
> > > > 
> > > > 
> > > > I like the simplicity it offers in terms of specification, with the current proposal of requiring `nameOfVendor` being a valid scheme.
> > > 
> > > 
> > > It's simple, but on the other hand, the more simple it is, the more will it interfere with normal URIs, where the pseudo-scheme will actually be interpreted as the first segment of a relative path. In view of this, perhaps having only `__nameOfVendor_vendorLinkType` would be an even better solution.
> > 
> > 
> > How can it be misinterpreted and how does allowing `_` solves that? The scheme is mandatory so if you don't throw away the leading `__` it's not a valid URI. When you strip the leading `__` you have valid scheme so there is no risk for misinterpretation.
> 
> Oh, I somehow thought that we also had "relative URIs" in mind, but I suppose we haven't until that is clearly stated. I may have been experimenting too much with utilities like this one, which understands that `__Wolfram_foo:bar` doesn't have a scheme:

Ok that explains how it can be misinterpreted. However, I still don't understand how allowing `__Wolfram_foo` solves anything? To me it sounds more like an argument to not have pseudo schemes at all.

**Comment by otronarp** [comment]
> > So if we want to stick with URIs, perhaps it's better to always require valid URIs and add markup that says that if a tool doesn't recognise the scheme don't make it a link and this is an alternative text that you should show if the link text is missing.
> 
> That wouldn't work with the intention of supporting _lesser known schemes_. For example, a user with an installation of System Modeler could use links with the `wsm` scheme, expecting other tools to send these to the operating system for interpretation. I suppose users could find this useful also for schemes that no Modelica tool is aware of.

Isn't that covered by `%[use the system for this link](wsm:foo)` and `%(wsm:foo|do not use the system for this link)`

**Comment by henrikt-ma** [comment]
> Ok that explains how it can be misinterpreted. However, I still don't understand how allowing `__Wolfram_foo` solves anything? To me it sounds more like an argument to not have pseudo schemes at all.

It could be an argument to not have pseudo-schemes at all, but as we already have `variable:` and `plot:`, the beauty of just having URI references has already been lost.  Maybe things would come into a different light if we first got rid of `variable:` and `plot:`.  For `plot:`, I'm hoping that the new Modelica URIs combined with allowing relative references in links will eventually allow a `Plot` to be referenced using just a fragment specifier.  The `variable:` presents a different kind of challenge, if we want to preserve the same kind of encoding convenience as for the variable replacements (applying `component-reference` parser, and not doing URL encoding).  Maybe the encoding convenience would have to be sacrificed, so that a link to a variable would (in a future with more powerful Modelica URIs) take the form of a (Modelica URI) relative reference with just a `component` query…

With `variable:` and `plot:` out of the way, only the vendor-specific links remain.  One easy way to structure these without interfering with general URI syntax would be to move the `__nameOfVendor` outside the link parentheses:
- `%[10 s]__Wolfram(?duration)` (omitting vendor-specific scheme)
- `%[10 s]__Wolfram(wsm:?duration)` (with vendor-specific scheme)

(I don't see much use for the `__nameOfVendor_vendorLinkType` form in this case, as the type of link is naturally represented with a vendor-specific scheme.)

**Comment by henrikt-ma** [comment]
> > > So if we want to stick with URIs, perhaps it's better to always require valid URIs and add markup that says that if a tool doesn't recognise the scheme don't make it a link and this is an alternative text that you should show if the link text is missing.
> > 
> > That wouldn't work with the intention of supporting _lesser known schemes_. For example, a user with an installation of System Modeler could use links with the `wsm` scheme, expecting other tools to send these to the operating system for interpretation. I suppose users could find this useful also for schemes that no Modelica tool is aware of.
> 
> Isn't that covered by `%[use the system for this link](wsm:foo)` and `%(wsm:foo|do not use the system for this link)`

OK, I see.  I suppose that could work too, and that a variant of this would be to use the same link text in both cases, and just a symbol to indicate that the link shouldn't be sent to the system:
- `%[use the system for this link (optional link text)](wsm:foo)`
- `%[do not use the system for this link (mandatory text)]*{wsm:foo}`

The main difference to the current proposal seems to be whether the scheme is expected to convey the name of the vendor defining the scheme in the same way as for the vendor-specific annotations.  Other than that, this looks like a clean design to me.

**Comment by henrikt-ma** [comment]
It would be nice if we could settle on a design for vendor-specific links in the upcoming phone meeting.

Trying to summarize the discussion so far, I think these are the main candidates:
- `%[mandatory-link-text](__NameOfVendor:…)`
  - Example: `%[10 s](__Wolfram:?duration)`
  - Pros: Style reminds of other links?
  - Cons: Not a valid scheme, hence technically in the form of a relative reference.  Each vendor is forced to use its own name as only scheme.
- `%[optional-link-text](URI|mandatory-alternative-text-if-link-text-is-missing)`
  - Example: `%[10 s](wolfram:?duration|)`
  - Pros: Generalizes idea of vendor-specific link to links that shall not be passed to system.
  - Cons: Not clear which links that are vendor-specific markup.  Two places to specify link text?  Subtle markup when alternative text is empty.
- `%[mandatory-link-text]__NameOfVendor(URI-reference)`
  - Example: `%[10 s]__Wolfram(?duration)`
  - Pros: Clear presence of vendor name.  Vendor freedom to design its own vendor-specific URI schemes.
  - Cons: Specifically designed for vendor-specific links.

**Comment by HansOlsson** [comment]
Hmmm... I'm a bit unsure how this will work in practice, and before looking at the details I have some general comments:

- Assuming a tool has some way of linking to some setting such as duration (I assume that is what the examples show), it would seem fairly normal that some other tool have a similar capability as well. How do we combine the two in good way in the same text?
- In some cases it seems that one tool would prefer having a text without linking to anything. Obviously it can be faked with a pseudo-link etc. But should it be directly supported? And if so, would that mean that we can ignore the link-issue since the entire text-fragment can tool-specific?

**Comment by henrikt-ma** [comment]
> Hmmm... I'm a bit unsure how this will work in practice, and before looking at the details I have some general comments:
> 
> * Assuming a tool has some way of linking to some setting such as duration (I assume that is what the examples show), it would seem fairly normal that some other tool have a similar capability as well. How do we combine the two in good way in the same text?

Good point.  It would be nice if we could handle this case as well, but I wouldn't consider it a necessary feature – being able to support one vendor link is still better than nothing.  Anyway, let's add an alternative to the poll to represent this idea:
- E. `%__NameOfVendor1(URI-reference)…__NameOfVendorN(URI-reference)[mandatory-link-text]`
  - Example: `%__Vendor1(?duration)__Vendor2(experiment:/length)[10 s]`
  - Pros: Allows more than one vendor-specific link attached to the same alternative link text.  When link text is just an alternative text (and mandatory), it uses a different position than when it is required to be shown (but optional).
  - Cons: Perhaps confusing with link text sometimes appearing before and sometimes after link.

> * In some cases it seems that one tool would prefer having a text without linking to anything. Obviously it can be faked with a pseudo-link etc. But should it be directly supported? And if so, would that mean that we can ignore the link-issue since the entire text-fragment can be tool-specific?

The intention is that "vendor-specific link" is actually more of a "vendor-specific markup with link-like syntax".  What a vendor does with its "links" should be left to the vendor.  I'm not sure I understand what the "link-issue" is, as a tool that doesn't recognize any of the vendor-specific links should only show the mandatory alternative text.  The use of a URI reference here is not meant to imply that some kind of link should actually be generated, but it uses an already established mechanism as a structured way of encoding vendor-specific information.

Is this an example of what you are describing (using alternative E for syntax)?
```
To edit the model, use %__Wolfram(string:/MC)__OSCM(app:MOEdit?name)[your favorite Modelica editor].
```

**Comment by henrikt-ma** [comment]
I think that by now, the term _vendor-specific link_ has proven itself too misleading for something that really isn't intended to only be used for links.  I'll update the text to say _vendor-specific markup_ instead, and present it separate from the markup for links.

In the last phone meeting, @HansOlsson expressed a desire for a design that doesn't restrict the vendor link to a URI reference, that it should be up to the vendor to decide whether to use a URI reference or something else.  I find it a valid remark, so I'll propose two variations of alternative E:
- F1. `%__NameOfVendor1(text-no-escapes)…__NameOfVendorN(text-no-escapes)[mandatory-link-text]`
  - Example: `%__Vendor1(?duration)__Vendor2(calc%28StopTime-StartTime%29)[10 s]`
  - Pros (in addition to those for E): Avoids hard choice of escape sequence (compare alternative F2 below).
  - Cons (in addition to those for E): A vendor can't define its own escape sequence like `%)` to be a non-terminating `)`.
- F2. `%__NameOfVendor1(dollar-escaped-text)…__NameOfVendorN(dollar-escaped-text)[mandatory-link-text]`
  - Example: `%__Vendor1(?duration)__Vendor2(calc(StopTime-StartTime$))[10 s]`
  - Pros (in addition to those for E): Escape sequence for `)` clearly reminds of what it stands for.
  - Cons (in addition to those for E): The use the dollar sign (`$`) as escape character is unusual, and means that `$` itself needs to be encoded using an escape sequence such as `$$`.

Regarding the choice of `$` as escape character in alternative F2: Some other alternatives were not chosen for different reasons:
- `\` is the escape character of Modelica string literals, and multiple layers of escape sequences using the same escape character is never nice.  For example, the backslash itself will appear as `\\\\` (four backslashes – counting them is getting hard) in the Modelica string literal.
- `%` is the escape character of URL encoding, making it cumbersome to use URI references for vendor-specific markup.
- `#` and some other characters have special roles in URI syntax that would make them a bad choice for vendors wanting to use URI references.
- `!` and some other characters are similar to `$` with respect to Modelica string syntax, URL encoding, and URI syntax.  Between them, the choice of `$` was merely based on gut feeling.

**Comment by henrikt-ma** [comment]
I've updated the proposal now along the lines of alternative F1 above.  This is a pretty big change, more or less putting us back on square one.  @HansOlsson, I'd appreciate if you could start by telling us whether you think the proposal is better now than before – if not, it probably better to go back to what we had before (alternative A) while discussing how to make it better.

**Comment by henrikt-ma** [comment]
As #2710 is meant to be the last merge of the branch _MCP/0033_, I've now changed this PR to merge directly into _master_ instead.

**Comment by HansOlsson** [comment]
Possibly discuss at next phone meeting, note that it is a rather large change with several parts - and in particular contains vendor-specific parts of annotations.

**Comment by henrikt-ma** [comment]
To me, this one is a high priority, as it is probably our last opportunity to get the figure annotations "right" before they become part of a released version.

The issues were brought up well in advance of the release, so that they could be fixed in timely manner, and all comments have been responded to since well over a month.

**Comment by HansOlsson** [comment]
Plan to resolve this. @DagBruck provide more feedback.

Ok that DS and Wolfram proceed with this?
Agreement.

**Review by DagBruck — APPROVED** [review]
As I understand it, a key point here is the **optional** addition of vendor-specific extensions, and the only requirement on other tools is to filter out the parts specifying unsupported extensions. So the absolute minimum support is to recognize the syntax and ignore what you don't support.

**Comment by henrikt-ma** [comment]
> As I understand it, a key point here is the **optional** addition of vendor-specific extensions, and the only requirement on other tools is to filter out the parts specifying unsupported extensions. So the absolute minimum support is to recognize the syntax and ignore what you don't support.

Right, so then you want a syntax that makes this reasonably easy.  The next question is whether the form looks flexible enough to you when you think about possible future uses of vendor-specific markup for your tool?

**Comment by henrikt-ma** [comment]
I suggest that we also wait for a final review from @otronarp, considering that he has not been active in the discussion since 2020-10-20.

**Comment by HansOlsson** [comment]
I noticed that there were conflicts, and looking at "Resolve conflicts" that resolution looked plain messed up.

**Comment by henrikt-ma** [comment]
> I noticed that there were conflicts, and looking at "Resolve conflicts" that resolution looked plain messed up.

Resolved.

**Comment by henrikt-ma** [comment]
I think we'll have to assume that @otronarp would have made his comments earlier if he had any.

**Pull request merged**
