### PR TITLE
Name of the game

### PR DESCRIPTION
**Pull request by henrikt-ma**
In the name of this PR, _the game_ refers to the simplified modeling language being defined in this MCP.  The goal of this PR is to settle a name for this language.

Initiating PR as draft to reflect that it is currently in a state where candidate names are collected, along with pros and cons of the various alternatives.

Let's generously accept more candidates as well as additional pros and cons for any of the names in this early stage of the PR.  We can slow down the process once we start having web meeting discussions about the content.

### CODE REVIEW

**Comment by HansOlsson** [comment]
"Intermediate Representation" does to me indicate a fairly different representation, especially as many use it for 3-address code (such as p-code) or stack-based ones (such as CIL), and both of them are at a considerably lower level.

"Lowered Modelica" is just weird to me; looking at https://en.wiktionary.org/wiki/lower#English the closest definition is "To reduce to single machine instructions, as part of compilation of a program", and that seems even further off than intermediate representation.

**Comment by olivleno** [comment]
"flat Modelica" as an established term that people can relate to is in my view the strongest argument. 
Due to the fact that as of today tools provide different solutions under this term should give the freedom to have just another solution, but one that shall be officially standardized.

**Comment by olivleno** [comment]
Web Meeting (Hans, Henrik, Gerd, Martin, Oliver)
It can be considered flat even though arrays are preserved.
In OM scalarization happens in the back-end and is not considered part of the flattening.

Are there any alternative proposals?

**Comment by casella** [comment]
> In OM scalarization happens in the back-end and is not considered part of the flattening.

For the record, if the old backend is used, scalarization takes place in the frontend. The new frontend moved it, so it is now the last part of the flattening process, which can be skipped. In this case, the new backend takes care of scalarization if and where needed. But it's still very much work in progress 😅

**Pull request merged**
