### PR TITLE
Initial commit of name-mapping.md

### PR DESCRIPTION
**Pull request by henrikt-ma**
Opening this for discussing the design of name mapping for Flat Modelica.  The content to be discussed is in the new file [_name-mapping.md_](https://github.com/henrikt-ma/ModelicaSpecification/blob/MCP/0031%2Bname-mapping/RationaleMCP/0031/name-mapping.md).

Since I haven't seen a procedure yet for MCP work organized using labels, I'm doing this for now using a draft PR instead.

### CODE REVIEW

**Comment by mtiller** [comment]
My opinion: invest this energy into a proposal to add "heredocs" and just be done with it.  It would benefit the language as a whole (*e.g.,* embedding HTML in annotations) and you could just get rid of all this quoting/unquoting/escaping stuff.  In Javascript, they use `` ` ``, in Python they use `'''` and `"""`.  I'd probably lean toward supporting both `` ` `` (see below) *and* `"""` because less chance of interaction with embedded Markdown, *e.g.,*

```
model """ManglingTest"""
  parameter Real `root.mm[1].p` = 2.0;
  Real `root.mm[1].arr[1]`;
  Real `root.mm[1].arr[2]`;
  Real `root.mm[1].x` = `root.mm[1].arr[1]` + `root.mm[1].arr[2]`;
  parameter Real `root.mm[2].p` = 3.0;
  Real `root.mm[2].arr[1]`;
  Real `root.mm[2].arr[2]`;
  Real `root.mm[2].x` = `root.mm[2].arr[1]` + `root.mm[2].arr[2]`;
  parameter Real `root.m.p` = 4.0;
  Real `root.m.arr[1]`;
  Real `root.m.arr[2]`;
  Real `root.m.x` = `root.m.arr[1]` + `root.m.arr[2]`;
  Real `y` = `root.m.x`;
equation
  der(`root.mm[1].arr[1]`) = `root.mm[1].p`;
  der(`root.mm[1].arr[2]`) = 1.0;
  der(`root.mm[2].arr[1]`) = `root.mm[2].p`;
  der(`root.mm[2].arr[2]`) = 1.0;
  der(`root.m.arr[1]`) = `root.m.p`;
  der(`root.m.arr[2]`) = 1.0;
end """ManglingTest""";
```

**Comment by mtiller** [comment]
Although I must say I disagree with the premise that Flat Modelica should be a subset of Modelica.  It certainly doesn't need to be.  You could reuse a huge amount of the grammar between them without having to prescribe this requirement.  BTW, why are you quoting `ManglingTest` and `y`.  These are both valid `IDENT`s and component references so why quote it?

**Comment by HansOlsson** [comment]
My comments:
* I would say that there are two alternatives - either we standardize such a mangling syntax for names, or we allow the declaration of variables with hierarchical names in Flat Modelica. (The latter is similarly to comment by @mtiller that we could reuse large parts of the grammar without having it as a subset of Modelica). And I don't know if we have considered the other option.
* I might be missing something, but to me it seems as if: A missing requirement is that the mangled names should be unique. In particular `foo [ 1, 2 ]` is given as an example of a component reference (and space is explicitly allowed). But that is the same as `foo[1,2]`, and if the pre-mangled name should include space we should specify exactly how many and where, and I couldn't find that.
* As indicated in #673 other languages seems to design their heredocs/raw literal string syntax to minimize interference with their existing syntax, and thus I think we need to consider the exact syntax carefully. However, I believe such support would primarily benefit things like writing HTML-documentation, and the quoting of quoted names is just a minor annoyance here.

**Comment by christoff-buerger** [comment]
@henrikt-ma: I like your proposal a lot. I think it catches all requirements. Of course, upquoting already quoted names will result in hard to read names; but I think that quoted names are the exception and not common -- we do not have to optimize the exceptional case.

I would only like to avoid the following of your proposal
 
 > Note that the same component reference may appear with different formatting in different places of the same Flat Modelica model.

which is related to what @HansOlsson notes:

 > [...] A missing requirement is that the mangled names should be unique. In particular foo [ 1, 2 ] is given as an example of a component reference (and space is explicitly allowed). But that is the same as foo[1,2], and if the pre-mangled name should include space we should specify exactly how many and where [...].

To that end, I would propose, that structural parts, when upquoting, must not contain whitespace. You already prohibit comments, so why not prohibit whitespace in structural parts in general? Doing so we have
 - Valid upquoting results `'\'I am a crazy\'[1,2].\'really crazy nested component reference\'[1, 3]'`
 - whereas the following is invalid `'\'I am a crazy\'[1, 2].\'really crazy nested component reference\'[1, 3]'`

# Heredocs and raw literal string syntax

I think this is a different topic, that can be improved separately. The issue is, that heredocs miss essential traceability requirements; they are meant to ease the embedding of code for third-party languages. To that end, bidirectionality is not required; heredocs focus on convenient code embedding, not unique code mangling within the same language. But we need bi-directional mapping of names.

I think the question of @mtiller shows the misunderstanding:

 > BTW, why are you quoting ManglingTest and y. These are both valid IDENTs and component references so why quote it?

Both are quoted in the example, because as Henrik explains, he investigates the use-case of a tool that naively applies full scalarization, i.e.,

 > [...] every Flat Modelica component reference refers to a scalar variable.

The reason to quote both is, because they are upquoted according to a unique, deterministic, bi-directional flattening method (which applies full scalarization); thus a respective downquoting considering full scalarization yields the original names.

You can best understand this when considering the use-case of sequential model processing, where each processing step may further upquote or downquote the previous step's result. We can for example partially scalarize the model
```
model M
    model MM
        Real x[3] = 3;
    model MM;
    MM m[2];
end M;
M m;
```
to
```
model M
    Real 'm.x[1]' = 3;
    Real 'm.x[2]' = 3;
    Real 'm.x[3]' = 3;
end M;
M m;
```
followed by another processing to
```
Real 'm.\'m.x[1]\'' = 3;
Real 'm.\'m.x[2]\'' = 3;
Real 'm.\'m.x[3]\'' = 3;
```
Downquoting twice will yield the original model, as it should be (going the tool chain backwards).

This is different to a tool doing it all in one step, which yields:
```
Real 'm.m.x[1]' = 3;
Real 'm.m.x[2]' = 3;
Real 'm.m.x[3]' = 3;
```

In terms of heredocs, we are talking about nested heredocs of the same language constructed by sequences of tool applications. I do not see how that can be achieved without nested quoting.

**Comment by henrikt-ma** [comment]
> * I would say that there are two alternatives - either we standardize such a mangling syntax for names, or we allow the declaration of variables with hierarchical names in Flat Modelica. (The latter is similarly to comment by @mtiller that we could reuse large parts of the grammar without having it as a subset of Modelica). And I don't know if we have considered the other option.

Yes, we have.  While it looks like an appealing strategy on first glance, the problem is that parsing expressions gets unnecessarily complicated when you don't see at the grammar level what is an identifier, and what is a hierarchical expression.  You'd need to perform some sort of extra pass once all variable declarations have been read, where you identify what is what in an expression.  A tool would be able to do it, but it still makes the code extremely hard to see through for a human.

**Comment by henrikt-ma** [comment]
> To that end, I would propose, that structural parts, when upquoting, must not contain whitespace. You already prohibit comments, so why not prohibit whitespace in structural parts in general? Doing so we have
> 
> * Valid upquoting results `'\'I am a crazy\'[1,2].\'really crazy nested component reference\'[1, 3]'`
> * whereas the following is invalid `'\'I am a crazy\'[1, 2].\'really crazy nested component reference\'[1, 3]'`

The reason for allowing whitespace was simply that I didn't see a need to forbid it, thereby allowing people and tools to follow the same whitespace conventions inside their Flat Modelica identifiers as in ordinary expressions.  I imagined that a tool would always parse the Flat Modelica identifiers anyway to construct the result variable names, and then the whitespace in the Flat Modelica identifiers would disappear naturally along the way and not cause any issues for the tools.

Anyway, with such strong (100%) agreement between all comments on this matter (you and @HansOlsson), I'll update the proposal accordingly.

**Comment by christoff-buerger** [comment]
@henrikt-ma: Thank you! Looks good now.

In the upquoting examples table we have `foo[1,2].bar` which is mapped to `'foo[1,2].bar'`. Considering the whitespace changes, we could even have `foo[1, 2].bar` or `foo[1 /*rows */, 2 /* columns */].bar`, both are also mapped to `'foo[1,2].bar'` now.

Thus, the mapping is not preserving whitespace for which reason it is not completely bidirectional; but that is fine with me. I do not think to preserve whitepsace, including comments, is of importance.

**Comment by henrikt-ma** [comment]
@christoff-buerger: After messing around with the Github online editor for a while, I think I've got your example covered…

**Pull request merged**
