### PR TITLE
New latex ml

### PR DESCRIPTION
**Pull request by HansOlsson**
Including 0.8.4 changes for the splitting of files.
It took a bit longer than planned because I had to track down the issue with images (and I should likely file a bug-report for it.)

### CODE REVIEW

**Comment by dietmarw** [comment]
@sjoelund You should update the docker image aswell since that would also allow the usage of subfiles then.

**Comment by HansOlsson** [comment]
I have now investigated further.

We can now use standard LaTeXML 0.8.4 (so no need for a special hack) and still get nice anchors, and also chapter names:

- Just use `--splitnaming=labelrelative`; and it works now!
- The downside is that all old references for specification.modelica.org would cease to work. That can be handled by adding file-links (soft or hard). Only about 30 links so should be straightforward, but I don't know how to do it as part of process.

**Comment by HansOlsson** [comment]
To clarify: I haven't committed that change of Makefile _yet_; but can do that - together with the links.
It requires that all chapters have a label - explaining the last commit.

**Comment by sjoelund** [comment]
#2546 has latexml 0.8.4 instead of Hans patched version.

**Comment by HansOlsson** [comment]
I have now added the soft links for previous version as part of Jenkins (hoping that suffices), and changed to use the new labelrelative.

**Comment by HansOlsson** [comment]
I could even see that the generated symlinks seem to work, even when downloaded to Windows.
(After realizing I had to unzip as Admin! :man_facepalming: )

**Comment by HansOlsson** [comment]
Can this be approved?

**Comment by dietmarw** [comment]
I did not have time to run this on my machine but if you are fine I can silently approve it.

**Comment by HansOlsson** [comment]
> I did not have time to run this on my machine but if you are fine I can silently approve it.

That would be appreciated.

**Pull request merged**
