### PR TITLE
Move the logo from abstract to title page

### PR DESCRIPTION
**Pull request by dietmarw**
It looked strange to have the logo appearing on the second page instead of the title page.

### CODE REVIEW

**Comment by dietmarw** [comment]
I see. BTW is there also a preview of the HTML version for the PRs? I can find the artifacts (pdf and tarball) but not a served version.

**Comment by HansOlsson** [comment]
> 
> 
> I see. BTW is there also a preview of the HTML version for the PRs? I can find the artifacts (pdf and tarball) but not a served version.

Good question, I don't know. 
For some reason I tested it locally (using the "command line instructions").

**Comment by dietmarw** [comment]
So I made the logo on title page conditional for PDF only. I can not really test it for HTML since my latexml version is still on  0.8.2. So would be good if you could double check this @HansOlsson

**Comment by dietmarw** [comment]
Should be fine now. Checked both the PDF and the HMTL generated by jenkins (the manual way via download and extract locally)

**Pull request merged**
