### PR TITLE
Clarify DAE representation of discrete equations

### LINKED ISSUE #3127: Missing equation in appendix B regarding discrete equations
[Appendix B](https://specification.modelica.org/maint/3.5/modelica-dae-representation.html) of the MLS contains the mathematical descriptions of hybrid DAEs corresponding to flattened Modelica models.

Equation (B.1b) corresponds to when-equation determining the values of the discrete variables showing up on their RHS. As I understand it, the "otherwise" section should also mention Modelica variables of discrete-valued types _m_, besides Real discrete variables _z_, i.e.:
```
z = pre(z)
m = pre(m)
```
For example, in this model
```
model M
  Boolean b(start = false, fixed = true);
  Integer i(start = 0, fixed = true);
equation
  when sample(0,1) then
    b = not(pre(b));
    i = pre(i) + 1;
  end when;
end M;
```
the equations (B.1b) become:
```
0 = b - not(pre(b))
0 = i - pre(i) - 1
```
at events and 
```
b = pre(b)
i = pre(i)
```
otherwise.

Adding @bernhardbachmann, @kabdelhak, @phannebohm, @AnHeuermann to the loop.

### PR DESCRIPTION
**Pull request by henrikt-ma**
Fixes #3127.

### CODE REVIEW

**Review by casella — APPROVED** [review]
LGTM. Thanks @henrikt-ma for opening the PR!

**Review by HansOlsson — CHANGES_REQUESTED** [review]
The previous variant made it easy to have an implicit equation for z at events, that is lost.
As indicated elsewhere I believe that having z=pre(z); and 0=f_z(v, c); as two cases make the actual semantics clearer.

**Comment by casella** [comment]
> The previous variant made it easy to have an implicit equation for z at events, that is lost. As indicated elsewhere I believe that having z=pre(z); and 0=f_z(v, c); as two cases make the actual semantics clearer.

See comment [here](https://github.com/modelica/ModelicaSpecification/issues/3127#issuecomment-1072279723).

**Review by HansOlsson — APPROVED** [review]
Ok, add clarification later.

**Pull request merged**
