### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by beutlich**
Just to not forget it.

### CODE REVIEW

**Comment by henrikt-ma** [comment]
This is a reason to replace the hard coded strings with content generated with git-describe.

**Comment by HansOlsson** [comment]
> This is a reason to replace the hard coded strings with content generated with git-describe.

Or macros.

**Comment by henrikt-ma** [comment]
> > This is a reason to replace the hard coded strings with content generated with git-describe.
> 
> Or macros.

What sort of macro would you use to make the version string reflect the tag/commit from which the products were built?

**Comment by HansOlsson** [comment]
> > > This is a reason to replace the hard coded strings with content generated with git-describe.
> > 
> > 
> > Or macros.
> 
> What sort of macro would you use to make the version string reflect the tag/commit from which the products were built?

See #2834 for what I intended.

**Comment by henrikt-ma** [comment]
> See #2834 for what I intended.

Right, that's a perfect change in its own right, and using git-describe to define that macro is beyond the scope of this PR.

**Review by HansOlsson — APPROVED** [review]
Looks good.

**Comment by beutlich** [comment]
This issue is still open while targeting the closed milestone 3.5. I propose to first get it resolved before the MA approval of MLS 3.5.

**Comment by HansOlsson** [comment]
> This issue is still open while targeting the closed milestone 3.5. I propose to first get it resolved before the MA approval of MLS 3.5.

This will be part of the agenda for the next phone meeting. To me this version-change, and actually changing the release information for 3.5 (including date should be fine) - whereas other changes of the text aren't that urgent; but it can be discussed.

**Pull request merged**
