### PR TITLE
Add missing period at end of last sentence in abstract

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Review by HansOlsson — COMMENTED** [review]
Looks ok, except that CI seems broken. @sjoelund ?

**Comment by henrikt-ma** [comment]
> Looks ok, except that CI seems broken. @sjoelund ?

No, that's because of the recent merge of the `size` thing.  There's a fix on the _cleanup/table-overuse_ branch.

**Comment by sjoelund** [comment]
I have restarted the jobs without pushing needed

**Review by HansOlsson — APPROVED** [review]
Looks good now.

**Pull request merged**
