### PR TITLE
Basic HTML layout improvements

### PR DESCRIPTION
**Pull request by henrikt-ma**
I am not at all an expert on web page layout and CSS, but I'd still like to propose these simple changes that at least I find making the HTML document easier to read.

By no means does this replace the need for putting the our CSS files in the hands of a skilled web designer, but until we find that person I think we need to get started with simple improvements. 

This PR does mainly two things:
- Improve readability of the navigation bar by:
  - making its size bigger.
  - Tweaking spacing.
  - Adjusting font size, weight, and text color.
- Improve readability of the document by:
  - Imposing a max width that will avoid too long lines when the document is opened in a wide window.  I know this is a sensitive topic, but I actually consider the max width proposed in this PR still too big, trying to please also those that like long lines.

### CODE REVIEW

**Review by HansOlsson — CHANGES_REQUESTED** [review]
I generally like the changes, but:
The navigation pane and title is white-on-black, but the main text is black-on-white (at least in IE and Firefox; I always have problems showing the navigation pane in other browsers from a local file).
I'm no UX expert, but to me it doesn't look good.

**Comment by MartinOtter** [comment]
> When looking around on the internet, using an inverted color scheme for side bars seems pretty common, and I think it is for good reasons.

But it is also pretty common to not use inverted color schemes, e.g. google.

Similar to Hans, I do not like an inverted color scheme, because I have difficulties to view it (in general, for my eyes, the contrast of white text on black backbround in a standard office room with standard daylight is much worse as the other way round; only if the environment is really dark, this is good).

**Comment by HansOlsson** [comment]
> > When looking around on the internet, using an inverted color scheme for side bars seems pretty common, and I think it is for good reasons.
> 
> But it is also pretty common to not use inverted color schemes, e.g. google.
> 
> Similar to Hans, I do not like an inverted color scheme, because I have difficulties to view it (in general, for my eyes, the contrast of white text on black backbround in a standard office room with standard daylight is much worse as the other way round; only if the environment is really dark, this is good).

I agree, and I tried to look around Stackoverflow, Discord, GitHub in beta mode, Visual Studio (as far as I recall) etc have a toggle between light-mode and dark-mode - that apply to both contents and main navigation. It may be that some have setting for mixing the two that I haven't found.

Some others only have light-mode (and rarely dark-mode), but this seem less common; at least for normally used elements. Some have inverted colors for some rarely used elements, like top-bar in GitHub. As far as I can see modelica.org is in this category and we want the specification to be consistent with that.

I don't know if we can easily make a dark-mode variant of the specification - but ideally that should just be a separate css-file; and I don't see that we should mix the two.

**Comment by henrikt-ma** [comment]
Great to get some comments!

The inspiration for the inverted color scheme was a generic image search for something like _sidebar table of contents css styling_, but I no longer remember the exact search terms I used.  It somehow happened that I found the ones with inverted color scheme most inspiring and most easily applicable to our table of contents.  (That Sublime Text, the editor I'm using all day long, also uses an inverted color scheme for the sidebar is of course also a circumstance that's hard to ignore.)  That's enough of background, let's now look at how we can avoid the inverted color scheme instead.

The challenge of our sidebar is the amount of content, in particular its long lines.  The current inverted color scheme allows a clear separation without using additional horizontal space for a separating border, but to really support the use of small screens, I actually think that a collapsable sidebar would be the way to go.  I suggest that we now begin with a layout aimed at larger screens, and save the problem of optimizing appearance on smaller screens for later.

> Some others only have light-mode (and rarely dark-mode), but this seem less common; at least for normally used elements. Some have inverted colors for some rarely used elements, like top-bar in GitHub. As far as I can see modelica.org is in this category and we want the specification to be consistent with that.

I had got the impression that modelica.org was considered almost as much in need of web designer attention as the specification.  While it is a page made for a rather different kind of content, I agree that there are elements that we should try to connect with, such as the use of small amounts of the "bouncing ball red".  I think we might well try to also get the almost-black text color and the "ball trace gray" into the design, even if modelica.org fails to do so.

> I don't know if we can easily make a dark-mode variant of the specification - but ideally that should just be a separate css-file; and I don't see that we should mix the two.

I don't think we should consider a dark mode at this time.  A dark side bar is one thing, but making the document content work against a dark background would require inverted figures in addition to the CSS styling.  Doable, but not something to prioritize, in my opinion.

I now hope to finish a proposal for a non-inverted sidebar in the new few days.  Concrete proposals for details of the design, or particular sites to use as inspiration (in addition to modelica.org), etc, are welcome at any time.

**Comment by henrikt-ma** [comment]
OK, how about that?

**Review by HansOlsson — APPROVED** [review]
Looks good now.

**Comment by HansOlsson** [comment]
> Looks good now.

Except for the javascript issue causing the build to fail.

**Pull request merged**
