### PR TITLE
Use colon instead of dash when attaching 'th' to ordinals

### PR DESCRIPTION
**Pull request by henrikt-ma**
Fixing issue reported by @HansOlsson in a comment to the recently merged #2789.  Fixing this generally: one more case besides the originally reported listing.

### CODE REVIEW

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Unfortunately I realized that colon here is Swedish (also when using numbers, e.g.: 1:a, 2:a, 3:e for 1st, 2nd, 3rd - Donald S. MacQueen "Using Numbers in English").

The English variants are i-th, i'th, and usually just ith (with i in italic mathematical style) https://en.wiktionary.org/wiki/ith
Looking more closely I believe the problem is that the problem might be that the hyphen in the comment text looks too long (due to the fixed-width font). 
Using ith (with i in math-style) or i'th when we cannot change style might be the best; or possibly just ith in the latter case.

**Comment by henrikt-ma** [comment]
Good research.  If the one without anything in between is the more common, it sounds like this is what we should try, unless we conclude that this doesn't work in listing comments, give priority to consistency over common style…

Did you figure out if there was a clear winner between hyphen and apostrophe, comparing commonality in technical literature?

**Comment by HansOlsson** [comment]
Seems it is difficult to search for that (even on GitHub) - both automatically and manually.
The only one I found so far was Graham, Knuth, Patashnik "Concrete Mathematics" that use kth  on page 23, with slightly different font for "k" (but not an italic font - just slightly different one).

**Comment by henrikt-ma** [comment]
> Seems it is difficult to search for that (even on GitHub) - both automatically and manually.
> The only one I found so far was Graham, Knuth, Patashnik "Concrete Mathematics" that use kth on page 23, with slightly different font for "k" (but not an italic font - just slightly different one).

Then I suggest we go for _k_ th (without that space necessitated by GitHub markdown) where math font is available, and `k'th` in listing comments.  OK?

**Comment by HansOlsson** [comment]
> > Seems it is difficult to search for that (even on GitHub) - both automatically and manually.
> > The only one I found so far was Graham, Knuth, Patashnik "Concrete Mathematics" that use kth on page 23, with slightly different font for "k" (but not an italic font - just slightly different one).
> 
> Then I suggest we go for _k_ th (without that space necessitated by GitHub markdown) where math font is available, and `k'th` in listing comments. OK?

Yes.

**Review by HansOlsson — APPROVED** [review]
Looks good now.

**Pull request merged**
