### PR TITLE
Fix typo in 'bibliograph'

### PR DESCRIPTION
**Pull request by henrikt-ma**
Trying to clean up no longer needed branches, and I don't understand why GitHub still says the commit on this branch isn't present on _master_…

### CODE REVIEW

**Comment by henrikt-ma** [comment]
Can someone explain what's going on here?  When I look at _master_, the fix is already in place.

**Comment by HansOlsson** [comment]
> Can someone explain what's going on here? When I look at _master_, the fix is already in place.

That was due to henrikt-ma-patch-4-1 which was merged through #2803 (to master).
I don't know why there were two PRs.

**Comment by henrikt-ma** [comment]
> > Can someone explain what's going on here? When I look at _master_, the fix is already in place.
> 
> That was due to henrikt-ma-patch-4-1 which was merged through #2803 (to master).
> I don't know why there were two PRs (or more specifically two branches).

Me neither, but what really puzzles me is why GitHub says that this branch still contains a change that can be applied to _master_: https://github.com/modelica/ModelicaSpecification/pull/2818/files

**Comment by dietmarw** [comment]
> My assumption is that you for unknown reason made two branches with the same contents; and some checks that the change isn't already there are done later.

That's exactly what happened: 
image

**Comment by dietmarw** [comment]
Btw, @henrikt-ma  you might wanna avoid creating PR branches on the main repo but in your fork instead. Also clean up merged branches afterwards ;-)

**Comment by beutlich** [comment]
I guess, if you merge this PR, you will see a commit w/o changes.

By the way, I have just enabled the auto-delete feature of merged branches (like we also set in the MSL repo):

grafik

**Comment by HansOlsson** [comment]
> Btw, @henrikt-ma you might wanna avoid creating PR branches on the main repo but in your fork instead. Also clean up merged branches afterwards ;-)

Yes! Would be appreciated.

**Comment by beutlich** [comment]
Rebasing and force-pushing that branch auto-closes the issue - nice!

**Comment by henrikt-ma** [comment]
> > Btw, @henrikt-ma you might wanna avoid creating PR branches on the main repo but in your fork instead. Also clean up merged branches afterwards ;-)
> 
> Yes! Would be appreciated.

Sure, cleaning up branches is what made me find this one.  I am also generally happy about the idea of branch hygiene in the central repo.

It is the convenient GitHub online editing that has tricked me into creating all these branches for changes so small that the branches are easily forgotten after merging.  Automatic cleanup makes perfect sense for this type of branches!  Now, does this mean that it becomes ok to keep creating central repo branches by GitHub online editing directly on the central repo?

**Comment by HansOlsson** [comment]
> It is the convenient GitHub online editing that has tricked me into creating all these branches for changes so small that the branches are easily forgotten after merging. Automatic cleanup makes perfect sense for this type of branches! Now, does this mean that it becomes ok to keep creating central repo branches by GitHub online editing directly on the central repo?

It would still be preferable to avoid it. However, as I understand it GitHub currently doesn't have good support for creating such branches in a local repository.

**Comment by dietmarw** [comment]
Alternatively use an editor with GitHub integration where you can simply create PR and follow them up from within the editor and which then also has LaTeX support. One I can recommend here is VSCode and the integration is shown here: https://code.visualstudio.com/docs/editor/github

**Pull request closed without merging**
