### PR TITLE
Amend recent change to defaultComponentName

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Comment by HansOlsson** [comment]
I don't see that the single quotes help here, especially as the `1` is in the code-font.

**Comment by henrikt-ma** [comment]
> I don't see that the single quotes help here, especially as the `1` is in the code-font.

We tend to do this everywhere there's just a single character in the code font.  It's easy to miss that there's something special about the character otherwise.

**Comment by HansOlsson** [comment]
Duplicate of #3186

**Comment by henrikt-ma** [comment]
This wasn't only about the quotes, and definitely not a duplicate of #3186.

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Looking at "Files changed" there are two changes:

- Conversion of `-` to `--` The other PR split that into two sentences, meaning it is no longer needed.
- Quoting. Part of other PR.

**Comment by henrikt-ma** [comment]
You are right, I was confused by the unresolved merge conflicts.  I'm sorry.  Closing.

**Pull request closed without merging**
