### PR TITLE
clarify: no connectors in functions

### PR DESCRIPTION
**Pull request by thorade**
this replaces #3

### CODE REVIEW

**Comment by thorade** [comment]
This time I will keep the rpository until the PR has been merged, to allow future edits.

Are connectors allowed in functions? They should be mentioned in either the may or may not group.
https://stackoverflow.com/questions/52756479/connector-as-function-input-argument-in-modelica

**Comment by HansOlsson** [comment]
Language group:
Should also change "i.e." to "e.g." to make it future-proof.

**Comment by HansOlsson** [comment]
However, you need to resolve the merge-conflict. I will then merge.

**Comment by thorade** [comment]
I resolved the merge conflict, and left out package.

**Comment by thorade** [comment]
After reading it once more, I suggest to add additional words in between to make it more readable. If that last (or any other) change is undesired please revert or change.

**Pull request merged**
