### PR TITLE
Don't treat 'nondiscrete' as keyword in listings

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Review by HansOlsson — COMMENTED** [review]
I agree that `nondiscrete `is no longer a keyword; and shouldn't be marked as keyword in the code examples.

However, it's not used in any code examples at the moment in the specification (afaik) - but only in historic references to the old keyword (when it was added and removed), and for that reason it makes sense to keep it as a keyword for the time being - since it would look odd if we state that discrete and nondiscrete were added as keywords (in some revision) and only one of them is marked as a keyword.

**Comment by henrikt-ma** [comment]
It's for our own sanity.  It gets crazy to not have the syntax highlighting rules in agreement with the current language specification.  I find it totally acceptable that something which is no longer a keyword displays like an identifier in the revision history.

**Comment by HansOlsson** [comment]
> It's for our own sanity. It gets crazy to not have the syntax highlighting rules in agreement with the current language specification. I find it totally acceptable that something which is no longer a keyword displays like an identifier in the revision history.

I would prefer this after 3.5; and see if we can redo the revision chapter more completely.

**Comment by henrikt-ma** [comment]
> I would prefer this after 3.5; and see if we can redo the revision chapter more completely.

Obviously  not a big deal if this gets in or not.  Anyway, I've restored the styling of `nondiscrete` when it appears in the revision history, so we get the best of both worlds.

The reason you're seeing all these PRs about trivial things now is that I'm just trying to cleanup among the comments left behind when working on the big cleanups like the `\lstinline` and the document index.  Having them fixed is just a matter of being in good shape for the release, but of course they can also be seen in the perspective of all the real problems we won't get fixed before the release.

**Review by HansOlsson — APPROVED** [review]
Looks good now.

**Comment by HansOlsson** [comment]
> Looks good now.

(Except for merge-conflict.)

**Comment by henrikt-ma** [comment]
> > Looks good now.
> 
> (Except for merge-conflict.)

Fixed.

**Pull request merged**
