### PR TITLE
Update to latexml 0.8.4

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
Where do you see -path? Or was that in the other PR?

```
Fatal:perl:die Perl died

	bad ns attribute! at /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/XML/LibXML.pm line 1687.

	In Post::Document[A4.html] ->addNodes

	 <= Post::CrossRef[@0x55af5e25d998]

1 warning; 1 fatal error
```

**Comment by sjoelund** [comment]
Maybe cherry-pick these commits into #2545? Note that the Jenkinsfile runs its own latexml commands and not the ones in the makefile.

**Comment by HansOlsson** [comment]
> Where do you see -path? Or was that in the other PR?

In Makefile of other PR, `--path=media`; so I guess it is necessary to repeat that in the CI-command as well.

**Comment by sjoelund** [comment]
That didn't seem to do it either :(

**Comment by sjoelund** [comment]
If I make derivationofstream.tex empty, it works...

**Comment by sjoelund** [comment]
It seems math context in subsection is no longer working in 0.8.4:
```diff
-\subsection{Connection of 3 stream connectors where one mass flow rate is identical to zero (N=3 and $\dot{m}_3=0$):}\doublelabel{connection-of-3-stream-connectors-where-one-mass-flow-rate-is-identical-to-zero-n-3-and}
+\subsection{Connection of 3 stream connectors where one mass flow rate is identical to zero}\doublelabel{connection-of-3-stream-connectors-where-one-mass-flow-rate-is-identical-to-zero-n-3-and}
```

**Pull request merged**
