### PR TITLE
Get rid of the obviously irrelevant parts of the grammar

### PR DESCRIPTION
**Pull request by henrikt-ma**
The goal of this PR is to get rid of the obviously irrelevant parts of the grammar.  At the time of writing, the branch to be merged doesn't yet make any changes to the grammar.  The idea is the working group should introduce these changes collaboratively, and everybody is invited to contribute.

### CODE REVIEW

**Comment by gkurzbach** [comment]
```
composition →
  (generic-element ;)*
  ( public (generic-element ;)*
  | protected (generic-element ;)*
  | initial? equation ( equation ; )*
  | initial? algorithm ( statement ; )*
```
When collecting equation sections from vectorized components it might be useful to allow dimensions after the **equation** and **algorithm** keyword, if someone wants to retain this structural information to take advantages from that. In this case the equations can be left unchanged, else the equations have to be duplicated and enriched with the right component indices. E.g.:
'equation [3] ....'
or in syntax:
```
  | initial? equation _array-subscripts_? ( equation ; )*
  | initial? algorithm _array-subscripts_? ( statement ; )*
```
This would be an extension of Modelica syntax.
```
  )*
  ( external language-specification?
   external-function-call? annotation-comment? ;
  )?
  ( annotation-comment ; )?
```

**Comment by henrikt-ma** [comment]
> When collecting equation sections from vectorized components it might be useful to allow dimensions after the `equation` and `algorithm` keyword

I like the idea, and I think it belongs to the item I put in the roadmap section [Flat Modelica 2.0](https://github.com/modelica/ModelicaSpecification/tree/MCP/0031/RationaleMCP/0031#flat-modelica-20-future-mcps).

**Comment by henrikt-ma** [comment]
I might remember wrong, but I thought we decided to merge this at the last web meeting.  Short of evidence thereof, I am at least marking this as _Ready for review_ now, as I think the discussion has slowed down enough.

**Comment by olivleno** [comment]
As decided in the web meeting, this all done for now and shall be merged.

**Pull request merged**
