### PR TITLE
Flat Modelica Variability and modifications

### PR DESCRIPTION
**Pull request by olivleno**
Capture the discussion w.r.t. variability and modifications.

### CODE REVIEW

**Comment by olivleno** [comment]
**Investigate the need for final**

Current uses of final:
(prevent misuse of a declared type by a later modification)
```
type T = Real (final min=0);
T x (min=1); //error in Modelica, could be accepted as more strict subtype
T y (min=-1); //error
```
```
record R
  Real x (final min=0);
end R;
R r (x(min=1));  //error
```
Do we need this level of safety in Flat Modelica?

(binding equation)
```
parameter Real x=1;
parameter Real y1=x+1;  //non constant default
final parameter Real y2=x+1;  //not allowed to change this parameter by the user
final parameter Real z=1;  //treated as constant Real z=1;
constant c = 1;
constant c1=c;  //ok
constant c2=z;  //error
```
Current variability and initializability
* constants that are treated as literals
* parameters set by the user but never change later
* parameters that change during initialization from a user-defined guess value
* parameters that change during initialization from a user-defined guess value

|                  |exact (by user) |approximate     |calculated (by model)|
| --              | --                    | --                      | -- |
| constant   | NA                  | NA                    | Real x=1; Real tau=4*arcsin(x);|
| parameter| Real x=1;  Real x=y+1  | Real x(fixed=false, start=1) | final Real x=y+1|

Do we need all this flexibility in Flat Modelica?

**Comment by henrikt-ma** [comment]
Something to think about until the next web meeting is the differences between the different built-in attributes.  It was said in today's meeting that we probably wouldn't need `final` to express that modifiers of `min` and `max` shouldn't be possible to override after translation, since the variability of `min` and `max` could be made `constant` in Flat Modelica (rather than `paramater`, as in full Modelica).

While most built-in attributes can be made `constant` in Flat Modelica, there is at least one important exception, namely `start` that definitely needs to be `parameter`.  (Regarding `nominal`, it should be noted that this actually has discrete-time variability in FMI, so we should probably at least make sure to not paint ourselves into a corner where Flat Modelica is forever more limited than FMI in this respect.)

Regarding `start`, below are some uses to keep in mind.  First, the most basic use of `start`:
```
model Decay "Non-final constant modification of 'start'"
  Real x(start = 1.0, fixed = true); /* Constant (literal) 'start' value that can be changed after translation. */
equation
  der(x) = -1;
end Decay;
```

The default `start` may also depend on parameters, still allowing the user to set different values after translation:
```
model Car "Non-final non-constant modification of 'start'"
  parameter Real initPressure = 2.6e5 "Default initialization of tire pressures";
  Real[4] tirePressures(each start = initPressure, each fixed = true); /* Parameter 'start' value that can be changed after translation. */
  …
end Car;
```

Then, a `start` that is a guess value controlled via another parameter:
```
model CirclePoint "Final non-fixed modification of 'start'"
  parameter Real phiStart = 0.0 "Initial angle";
  Real x(final start = cos(phiStart), fixed = false); /* Initialization only via 'phiStart'. */
  Real y(final start = sin(phiStart), fixed = false); /* Initialization only via 'phiStart'. */
equation
  x^2 + y^2 = 1.0;
  …
end CirclePoint;
```

Similar to the above, but `fixed` ("complicated" initialization via helper parameters only used for intermediate results during initialization):
```
model Phi "Final fixed modification of 'start'"
  parameter x0 = 1.0 "Rectangular initialization of x";
  parameter y0 = 0.0 "Rectangular initialization of y";
  parameter phi0(start = 1.0, fixed = false);
  parameter r0(start = 1.0, fixed = false);
  Real phi(final start = mod(phi0, 6.28), fixed = true); 
initial equation
  r0 * cos(phi0) = x0;
  r0 * sin(phi0) = x0;
end Phi;
```

The examples above don't cover all combinations of `start` expression variability, `final`, and `fixed`, but probably shed some light on the complicated matter of variable initialization, and should remind us that we also have the related roadmap item _Restricted rules for use of `start` attribute for parameter initialization_.  To me, the complicated interplay between `start`, `fixed`, and `final`, could be an indication that we should look for another solution than having `start` (and perhaps `nominal`) as built-in attributes, but I don't have any better ideas at the moment…

**Comment by olivleno** [comment]
Web-Meeting: 
```
model Phi "Final fixed modification of 'start'"
  parameter Real x0 = 1.0 "Rectangular initialization of x";
  parameter Real y0 = 0.0 "Rectangular initialization of y";
//  parameter Real phi0(start = 1.0, fixed = false);
  initial_value Real phi0 = 1.0;
//  parameter Real r0(start = 1.0, fixed = false);
  initial_value Real r0 = 1.0;
  Real phi; 
//  Real p(start=1e5);
  parameter Real p_start=1e5;
  Real p;
initial equation
  phi = mod(phi0, 6.28)
  r0 * cos(phi0) = x0;
  r0 * sin(phi0) = x0;
  p = p_start;
equation
  der(p)=1;
end Phi;
```

Issues with this approach:

* p_start would require an additional annotation to remove it from the results.
* p_start should show up in the UI as start value and not as parameter.


Benefits of this approach

* Get rid of the attribute with parameter variability start 
* Get rid of the attribute fixed.

**Comment by sjoelund** [comment]
A Modelica model with a `fixed=true` that has a nonlinear system of equations (the start-value influences the solution):
```
model M
  parameter Real y(fixed=false, start=1.0);
  parameter Real x(fixed=true, start=1.0) = f1(y);
initial equation
  y = f2(x);
end M;
```

**Comment by olivleno** [comment]
With
```
f1 = y^2
f2 = sin(x)
```
I implemented the model as
```
model M
  parameter Real y(fixed=false, start=1.0);
  parameter Real x(fixed=true, start=1.0) = y^2;
initial equation 
  y = sin(x);
end M;
```
This gives the following results: 
Dymola: x = y = 1.3864e-18
OMEdit: x = y = 0;
This means first we have to clarify what is the expected result.

* x=0 and y=0, is correct in the sense that it satisfies all equations but wrong as it does not appreciate x(fixed=true, start=1.0)
* x=1, and y=sin(1) is appreciating the x(fixed=true) and the initial equation
 
Not sure where in the Modelica Spec it is defined which constraint takes precedence?

If it is common sense that even a fixed=true variable can become an iteration variable, then the equations could be rewritten as: 
```
model M
//  parameter Real y(fixed=false, start=1.0);
  initial_value Real y =1.0;
//  parameter Real x(fixed=true, start=1.0) = y^2;
  initial_value Real x = 1.0;
initial equation
  x = y^2;
  y = sin(x);
end M;
```

**Comment by henrikt-ma** [comment]
I must admit that was actually disappointed to see SystemModeler build that model without any warnings.  My guess at what is missed is that we don't even look at `fixed` for a parameter with a declaration equation, simply assuming that `fixed = false`.

How would the model `M` above differ from the follow variant anyway?
```
model M_x_not_fixed
  parameter Real y(fixed=false, start=1.0);
  parameter Real x(fixed=false, start=1.0) = y^2;
initial equation 
  y = sin(x);
end M_x_not_fixed;
```

**Comment by HansOlsson** [comment]
> I must admit that was actually disappointed to see SystemModeler build that model without any error (or even warnings). My guess at what is missed is that we don't even look at `fixed` for a parameter with a declaration equation, simply assuming that `fixed = false`.

Actually the opposite giving the same result!

For a parameter the default is "fixed=true", https://specification.modelica.org/master/class-
predefined-types-and-declarations.html#real-type

And no equation is added to the initialization equation - i.e. the binding is used:
https://specification.modelica.org/master/equations.html#initialization-initial-equation-and-initial-algorithm

**Comment by sjoelund** [comment]
> How would the model `M` above differ from the following variant anyway?

```
Warning: The parameter x has fixed = false and a binding equation x = y ^ 2.0, which is probably redundant.
Setting fixed = false usually means there is an additional initial equation to determine the parameter value. The binding was ignored by old Modelica tools, but this is not according to the Modelica specification. Please remove the parameter binding, or bind the parameter to another parameter with fixed = false and no binding.
```

Is what I get :)

**Comment by sjoelund** [comment]
> ```
> model M
> //  parameter Real y(fixed=false, start=1.0);
>   initial_value Real y =1.0;
> //  parameter Real x(fixed=true, start=1.0) = y^2;
>   initial_value Real x = 1.0;
> initial equation
>   x = y^2;
>   y = sin(x);
> end M;
> ```

This has the problem that the tool generating flat Modelica needs to know that there is an algebraic loop and the start-value influences the solution (which might not be the case after some trivial symbolic manipulation).

> If it is expected that fixed=true always means that the variable get the start value, then the equations could be rewritten as:
> 
> ```
> model M
> //  parameter Real y(fixed=false, start=1.0);
>   initial_value Real y =1.0;
> //  parameter Real x(fixed=true, start=1.0) = y^2;
>   parameter Real x = 1.0;
> initial equation
>   y = sin(x);
> end M;
> ```

`y^2` is missing from this model.

**Comment by henrikt-ma** [comment]
> Actually the opposite giving the same result!

But we don't add `start`-equations for parameters or constants with `fixed = false` either, so I still don't see the point of setting `fixed = true`.

For purposes of Flat Modelica, is what we are trying to express any different from the following model, where the weird combination of a declaration equation and `fixed = true` is avoided?
```
model M_x_not_fixed
  parameter Real y(fixed=false, start=1.0);
  parameter Real x(fixed=false, start=1.0);
initial equation 
  y = sin(x);
  x = y^2;
end M_x_not_fixed;
```

**Comment by henrikt-ma** [comment]
> > How would the model `M` above differ from the following variant anyway?
> 
> ```
> Warning: The parameter x has fixed = false and a binding equation x = y ^ 2.0, which is probably redundant.
> Setting fixed = false usually means there is an additional initial equation to determine the parameter value. The binding was ignored by old Modelica tools, but this is not according to the Modelica specification. Please remove the parameter binding, or bind the parameter to another parameter with fixed = false and no binding.
> ```
> 
> Is what I get :)

OK, but that was for the original `M_x_not_fixed`, not for `M` where `x` has `fixed = true`.

**Comment by gkurzbach** [comment]
IMO, according to the spec the correct translation of
> ```
> model M
>   parameter Real y(fixed=false, start=1.0);
>   parameter Real x(fixed=true, start=1.0) = y^2;
> initial equation 
>   y = sin(x);
> end M;
> ```
would be
```
model M
//  parameter Real y(fixed=false, start=1.0);
  initial_value Real y =1.0;
//  parameter Real x(fixed=true, start=1.0) = y^2;
  parameter Real x = y^2;  // the start value is ignored because of the binding equation and the parameter remains
initial equation
  y = sin(x);
end M;
```
But what is with 
```
model M
  parameter Real y(fixed=false, start=1.0);
  parameter Real x(fixed=true, start=1.0);
 initial equation 
   x=y^2;
   y = sin(x);
 end M;
```
?
This should lead to an error (not solvable overdetermined system).

**Comment by henrikt-ma** [comment]
Regarding the "correct translation", I think we must make sure that there is a way to give guess values for all iteration variables, so omitting the `start` for `x` doesn't look right to me.

**Comment by henrikt-ma** [comment]
Some that don't have extensive experience with full Modelica may also be interested in the subtle difference between the following two parameters:
```
model M
  parameter Real r(start = 100);
  parameter Real s = 100;
end M;
```
When translated, the only difference between the initialization of the two parameters is that there shall be a warning about not having added a binding equation for `r`.

This rule should be the explanation why a combination of `fixed = true` and a declaration equation is allowed in full Modelica, because when the warning is addressed, one ends up with this:
```
parameter Real r(start = 100) = 50;
```

Now, imagine that `50` is replaced by an expression that pulls the parameter into a nonlinear equation system.  Then we need a guess value, and it would make sense to use `start` even though I doubt that this is clear from the specification.  Hence, I think it is safe to consider the combination of `fixed = true` and a declaration equation some sort of anomaly, that we can better think of as actually having `fixed = false`.

For Flat Modelica, it should be the responsibility of the full Modelica tool to generate the warning about missing binding equation, so there should be no need to distinguish the two variants.  To simplify our discussions about the initialization problem, I would therefore suggest that we don't consider declaration equations (only using them for constants).

Example 1: Instead of looking at the full Modelica parameter
```
parameter Real p = <binding>;
```
we look at this parameter instead:
```
parameter Real p(start = <guess>);
```

Example 2: Instead of looking at the full Modelica parameter
```
parameter Real p(start = <guess>, fixed = false) = <binding>;
```
we look at this parameter instead:
```
  parameter Real p(start = <guess>, fixed = false);
initial equation
  p = <binding>; /* Ideally, use equation with prescribed causality. */
```

Example 3: Instead of looking at the full Modelica algebraic variable
```
Real y = <binding>;
```
we look at this variable instead:
```
  Real y;
equation
  y = <binding>; /* Ideally, use equation with prescribed causality. */
```

Example 4: Instead of looking at the full Modelica algebraic variable
```
Real y(start = <guess>, fixed = false) = <binding>;
```
we look at this variable instead:
```
  Real y(start = <guess>, fixed = false);
equation
  y = <binding>; /* Ideally, use equation with prescribed causality. */
```

Note that this is only about reducing the number of variants to have in mind when thinking about how to express initialization in Flat Modelica; whether declaration equations are used in Flat Modelica is a different matter.

**Comment by henrikt-ma** [comment]
I've finally been able to make some progress on the proposal for how to simplify initialization, see: https://github.com/henrikt-ma/ModelicaSpecification/blob/MCP/0031%2Bvariable-initialization/RationaleMCP/0031/initialization.md

Note that the later part of the document (under the heading _Reducing full Modelica initialization to Flat Modelica_) is not up-to-date with the first part, as I still need to figure out a good way to express the intermediate stages between full Modelica and Flat Modelica.  Therefore, I think we should try to begin by primarily looking at the first part which only introduces the concepts used to describe initialization.  Maybe we can then work out some examples together during the upcoming web meeting to see how it works out.

Should I create a new PR for this branch?

**Comment by henrikt-ma** [comment]
Comments for today's web meeting:
- Doesn't look right when one finds comments like this in the discussion here:
  - _This PR is only for removing the obviously irrelevant parts of the grammar._
- Amount of discussion about full Modelica initialization is to me evidence that we need a more elementary model for initialization in Flat Modelica, making it a full Modelica problem to define the meaning of various combination of high-level constructs.

**Comment by henrikt-ma** [comment]
After merging with _MCP/0031_, it's clear that there are no changes worth preserving in this PR.  Hence, I suggest that we abort the PR and delete the _variability_modifications_ branch.

I think the most interesting part of the discussion is some of the example models that came up as examples of initialization in full Modelica, of varying degree of complexity.  For example, this one could be good to move over to #2748:
```
model Phi "Final fixed modification of 'start'"
  parameter x0 = 1.0 "Rectangular initialization of x";
  parameter y0 = 0.0 "Rectangular initialization of y";
  parameter phi0(start = 1.0, fixed = false);
  parameter r0(start = 1.0, fixed = false);
  Real phi(final start = mod(phi0, 6.28), fixed = true); 
initial equation
  r0 * cos(phi0) = x0;
  r0 * sin(phi0) = x0;
end Phi;
```

**Comment by olivleno** [comment]
Web Meeting
Decided to close now and carry over any interesting examples to the new PR's, e.g. [#2748](https://github.com/modelica/ModelicaSpecification/pull/2748)

**Pull request closed without merging**
