### PR TITLE
Do not incorrectly use import name

### LINKED ISSUE #2974: Meaning and restrictions for 'import names'
The term _import name_ seems to be used inconsistently, meaning that the uniqueness rule for qualified imports is unclear.  This issue looks like it could be a follow-up to #1573.

Searching for _import name_ in the sources gives me these three matches (ordered for purposes of this presentation):

1:
> Among the import names of qualified import-clauses in the \emph{instance} scope.  The import name of \lstinline!import A.B.C!; is \lstinline!C! and the import name of \lstinline!import D=A.B.C;! is \lstinline!D!.

2:
> Assume that we want to access the package \lstinline!MyLib.Pack2! in \cref{fig:roots} above, e.g.\ through an \lstinline!import!-clause \lstinline!import MyLib.Pack2;!. During lookup we first try to find a package \lstinline!MyLib! corresponding to the first part of the import name.  It is not found in the top-level scope since it has not previously been loaded into the environment.

3:
> Multiple qualified \lstinline!import!-clauses shall not have the same import name.

From 1 we seem to get a clear definition of what the _import name_ is, but then 2 speaks of the first part of the import name, which doesn't make sense in view of 1 where there's always just one part.

What is really meant by 3?  Is the purpose to forbid things like the following?
```
import Pack.{f, f};
```
That doesn't seem to correspond to one of the confusing situations discussed in #1573, making me think that the purpose of the rule is to rule out something else…

### PR DESCRIPTION
**Pull request by HansOlsson**
Closes #2974

### CODE REVIEW

**Review by henrikt-ma — CHANGES_REQUESTED** [review]
The change in itself is good, but may I suggest that for closing #2974 we should also do something to facilitate finding the definition of _import name_ from the only place remaining where it is used?

Suggestion:
- Introduce _import name_ with `\firstuse` and add it to the index.
- Add a link to the section with the definition:
> … shall not have the same import name (see \cref{simple-name-lookup}).

**Comment by henrikt-ma** [comment]
Maybe a better solution than adding a link to the section with the definition could be to instead move the rule to the section of the definition?

**Comment by HansOlsson** [comment]
> Maybe a better solution than adding a link to the section with the definition could be to instead move the rule to the section of the definition?

Having a separate definition for import-name seems a bit excessive based on how little it is used in the specification; and thus I used the first variant instead.

**Review by henrikt-ma — APPROVED** [review]
Looks good.

(What I was suggesting was something even more light-weight: like now with `\firstuse` and `\index`, but then moving the rule instead of adding the link to the section where the definition by means of `\firstuse` is found.)

**Pull request merged**
