### PR TITLE
Remove outdated link to doc.modelica.org

### PR DESCRIPTION
**Pull request by beutlich**
~~Only link to OM generated help of MSL v4.0.0.~~

Alternatively (and avoiding the version dependency in the specification) we can update http://doc.modelica.org/om/Modelica.UsersGuide.html to redirect to https://doc.modelica.org/Modelica%204.0.0/Resources/helpOM/Modelica.html.

### CODE REVIEW

**Comment by HansOlsson** [comment]
> Only link to OM generated help of MSL v4.0.0.
> 
> Alternatively (and avoiding the version dependency in the specification) we can update http://doc.modelica.org/om/Modelica.UsersGuide.html to redirect to https://doc.modelica.org/Modelica%204.0.0/Resources/helpOM/Modelica.html.

I agree that just one link would be preferable, but to me another way of reducing dependencies would be to just link to https://github.com/modelica/ModelicaStandardLibrary as that would seem like the natural landing point for someone interested in MSL. It may be that the actual overview (or user's guide) is a bit too hidden on that page, but then it would make sense to modify it to make it more visible.

**Comment by beutlich** [comment]
Fine for me to only link to https://github.com/modelica/ModelicaStandardLibrary.

And right, while `doc.modelica.org` is prominently display in various links at https://github.com/modelica/ModelicaStandardLibrary, we have no dedicated link to its Users Guide.

**Comment by HansOlsson** [comment]
> Fine for me to only link to https://github.com/modelica/ModelicaStandardLibrary.

Can you update the PR?

> And right, while `doc.modelica.org` is prominently display in various links at https://github.com/modelica/ModelicaStandardLibrary, we have no dedicated link to its Users Guide.

I leave that to MAP-Lib.

**Comment by beutlich** [comment]
> Can you update the PR?

Done.

**Review by HansOlsson — APPROVED** [review]
Looks good.

**Pull request merged**
