### PR TITLE
Initialization of variables in Flat Modelica using start('v') and guess('v')

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Comment by olivleno** [comment]
Web Meeting:
* Proposal to use initial algorithm instead initial equation
* Rejecting cyclic dependencies of parameter declaration equations is responsibility of Full Modelica, could be added later.
* Introducing new stuff to Flat Modelica will require additional effort for the compiler.

#### Simple case
```
  parameter Real p1 = 1;
  parameter Real p2 = 2*p1;
```
turned into:
```
  parameter Real 'p1' = 1;
  parameter Real 'p2' = 2*'p1';
```
which is syntactic sugar for:
```
  parameter Real 'p1';
  parameter Real 'p2';
initial equation
  start('p1') = 1;
  start('p2') = 2*'p1';
```

#### Variant of simple case
Full Modelica
```
  parameter Real p1 = 1;
  parameter Real p2;
initial equation
  p2 = 2*p1; //In this case p2 cannot be modified
```
turned into Flat Modelica:
```
  parameter Real 'p1' = 1;
  parameter Real 'p2';
initial equation
  'p2' = 2*'p1';
```
which is syntactic sugar for:
```
  parameter Real 'p1';
  parameter Real 'p2';
initial equation
  start('p1') = 1;
  'p2' = 2*'p1';
```
#### Variant Simple case using final
```
  parameter Real p1 = 1;
  final parameter Real p2 = 2*p1;
```
turned into:
```
  parameter Real 'p1' = 1;
  parameter Real 'p2';
initial equation
  'p2' = 2*'p1';
```
which is syntactic sugar for:
```
  parameter Real 'p1';
  parameter Real 'p2';
initial equation
  start('p1') = 1;
  'p2' = 2*'p1';
```


#### Advanced Example
```
  parameter Real p(fixed=false);
  Real x(start=p, fixed=true);
initial equation 
  p+p^3=9+x;
equation 
  der(x)=-x;
```
turned into:
```
  parameter Real 'p';
  Real 'x';
initial equation
  start('x') = 0;    // implicit
  guess('x') = ... start('x')... ; // implicit
  'x' = 'p'; 

  start('p') = 0;    // implicit
  guess('p') = ...; // implicit
  'p'+'p'^3=9+'x';
equation 
  der(x)=-x;
```

**Comment by HansOlsson** [comment]
Note that since we in Emphysis should consider clocked models for embedded systems we also have to consider how they initialize (or don't) - see #2624

**Comment by olivleno** [comment]
Web Meeting:
* Martin: Implementing the current proposal will require to make big changes:
** New concepts for the back-end that need to be managed like: code generation for initialization,...

* Henrik: Current implementations are more complicated, because many implicit things have to be considered.
* Gerd: Goal of Flat Modelica is to make more things explicit, This if going in the right direction.
* It's likely that different tools will produce slightly different initialization code, which will reveal inconsistencies that can then be resolved and standardized in Full Modelica.
* Henrik: Compared with the overall effort this is reasonable, given that this is adding significant value.
* Hans: It's not clear how guess instead of start will really help. It's hard to say how much this will really help to understand the issues. What we currently have in full Modelica is not too hard to handle. Not sure if there is any additional information for start value prioritization that we might be loosing.
* Henrik: This could easily be added as additional argument.
* Hans: Don't know what it means in terms of implementation effort.
* Henrik: Maybe we could first only remove start attribute in a first version, skip guess operator and only express start by start(v) using equations instead of a type. Beautfy of having it in the type is the concept of Modification in full Modelica, which does not apply to Flat Modelica. We gain a cleaner definition of types with only constant attributes.
* Martin: One could restrict what is allowed in flat Modelica vs. full Modelica.
* Henrik: in modified start values in deeply nested hierarchy would lead to long modifiers.

Proposals:
1. Delay this feature to version 2 (keep start as an attribute and semantics of final and fixed as in full Modelica).
2. Delay the decision until after simplifying modifications
3. Go with a compromise (only start without guess).
4. Restrict usage of start by removing it from the type attributes but allowing it to be modified in top level component declarations.
5. Accept the proposal.

Gerd: 2,4 We should make only well informed decisions. 4 would avoid things like start being passed around.
Martin: Ok: 1,4,(2), Nok: 5,(3)
Hans: Ok: 4, Not clear what to gain by 1 and 2, Not ready for 3,5
Henrik: 2,3: because not ready for 1,4 without understanding modification, 5 because proposal needs more work
Oliver: Ok: 4,3: acceptable compromise from user perspective,1 to get forward, Nok: 2,5 risk of getting stuck
Adrian: 4,5, might complicate debugging

4 seems acceptable by most.
Henrik: Yes, someone just has to show me how to implemented in the specification. We could have someone to spell it out and discuss in the context of modifications to proof it right or wrong.

Decision:
Martin will take care of making a proposal for the specification on restricting usage of start (not until next meeting, but soon after).
In parallel we will start working on modifications.

**Comment by henrikt-ma** [comment]
Comments for today's web meeting:
- I still believe in the use of equations rather than built-in attributes for expressing the initialization problem, as it provides a model with is both more elementary and at the same time offers great expressibility.
- Separation of component declarations and introduced equations for `start('v')` and `guess('v')` is a bit unfortunate, but seems like something we could address.
- Needs update regarding need to express acyclic binding constraint (we've noted that this check belongs to full Modelica, and should be checked when Flat Modelica is produced).
- Case of non-parameter with `fixed = false` and declaration equation should probably use normal (acausal) equation.
- Maybe readability would be considered improved by writing `'v'.start` and `'v'.guess` instead?  (Note that `start` and `guess` belongs to reserved part of namespace.)

**Comment by henrikt-ma** [comment]
This PR is obsolete.  I think we should just close it.

**Comment by olivleno** [comment]
Web Meeting: (Hans, Martin, Gerd, Henrik, Oliver)

After review decided to close as it is all covered in the latest agreed proposal on initialization.

**Pull request closed without merging**
