### PR TITLE
Work around broken tables

### PR DESCRIPTION
**Pull request by HansOlsson**
This is just an experiment to test the problem with LaTeXML texlive2022 and tables.

### CODE REVIEW

**Review by henrikt-ma — APPROVED** [review]
OK.  I assume CI builds are still not working for PRs?

**Comment by HansOlsson** [comment]
> OK. I assume CI builds are still not working for PRs?

Actually they seem to work.

**Comment by HansOlsson** [comment]
The conclusions are that:

- `\lstinline` messes up tables, especially if not in the first column. Strangely enough it worked in `\tablehead` -ah!
- Even using `\lstinline` indirectly through an identifier macro fails
- Using `{\lstinline!..!}` seems to work in table

**Comment by HansOlsson** [comment]
Closes #3156

**Pull request merged**
