### PR TITLE
Clean up quadrature listings

### PR DESCRIPTION
**Pull request by henrikt-ma**
This fixes issues with line breaks inside rest-of-line comments.

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]
Ok

**Comment by henrikt-ma** [comment]
@HansOlsson: Forgot to also merge?

**Comment by henrikt-ma** [comment]
Can we please avoid squashed merges, as it gives rise to branch deletion warnings that require extra work to ensure nothing was left behind in other repositories?

**Comment by HansOlsson** [comment]
> Can we please avoid squashed merges, as it gives rise to branch deletion warnings that require extra work to ensure nothing was left behind in other repositories?

Non-squashed merges sometimes create too many changes, which makes it harder to follow the history of the master branch.

**Comment by henrikt-ma** [comment]
The solution to that is to avoid fast-forward merges.

**Pull request merged**
