### PR TITLE
Update convertMessage to handle elements.

### LINKED ISSUE #2516: Something like convertMessage for components
Currently convertMessage can be used for classes that cannot be converted.

However, the same issue can occur for components - and it would be good to have something similar for that case, e.g. convertMessageElement

https://github.com/modelica/ModelicaStandardLibrary/issues/3455#issuecomment-593391633_

The benefits are:

- Users will get better diagnostics when converting their libraries
- Better check of conversions beforehand

### PR DESCRIPTION
**Pull request by HansOlsson**
Closes #2516

### CODE REVIEW

**Comment by HansOlsson** [comment]
@henrikt-ma  @sjoelund or others, would be good with a review of this one.

**Comment by henrikt-ma** [comment]
I'm sorry.  Our implementation of conversions is still lagging too much behind for me to be able to think through consequences.

**Review by sjoelund — APPROVED** [review]
I suppose since nobody implemented these things, we should accept it. This particular conversion is only to give messages so it is easy to ignore it without changing the resulting model anyway.

**Comment by HansOlsson** [comment]
> I suppose since nobody implemented these things, we should accept it. This particular conversion is only to give messages so it is easy to ignore it without changing the resulting model anyway.

True that it's easy to ignore.

However, it actually has been implemented for Dymola 2021x just in case.
No library uses it yet.

**Comment by sjoelund** [comment]
> However, it actually has been implemented for Dymola 2021x just in case.

I meant except Dymola :)

**Pull request merged**
