### PR TITLE
Name the HTML entry page 'index.html'

### LINKED ISSUE #3076: HTML entry page isn't index.html
Couldn't we be normal and rename _MLS.html_ → _index.html_?  That way, a link to the specification would look nicer, avoiding the _MLS_ abbreviation which is so often getting mixed up with with _MSL_, for example:
- https://specification.modelica.org/maint/3.5/

### PR DESCRIPTION
**Pull request by henrikt-ma**
Fixes #3076.

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
[sitemap,xml](https://github.com/modelica/ModelicaStandardLibrary/blob/gh-pages/sitemap.xml) should be updated, too, once it is merged, built and deployed.

**Review by sjoelund — APPROVED** [review]
The only weird thing I saw when testing this locally is that before the top would link to `/MLS.html` and now it links to `/` instead of `/index.html` . I guess latexml knows about index.html normal webserver configuration, but it does not work locally (you get the directory listing in both Chrome and Firefox).

**Comment by henrikt-ma** [comment]
> The only weird thing I saw when testing this locally is that before the top would link to `/MLS.html` and now it links to `/` instead of `/index.html` . I guess latexml knows about index.html normal webserver configuration, but it does not work locally (you get the directory listing in both Chrome and Firefox).

Yes, I also noted this surprising but welcome feature.

**Review by HansOlsson — APPROVED** [review]
ok

**Comment by henrikt-ma** [comment]
> [sitemap,xml](https://github.com/modelica/ModelicaStandardLibrary/blob/gh-pages/sitemap.xml) should be updated, too, once it is merged, built and deployed.

Do you mean deployed at https://specification.modelica.org/master/ or deployed in a different sense?  Would now be the appropriate time for opening an MSL issue to get it done?

**Pull request merged**
