### PR TITLE
Remove incorrect plural 's'

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Review by eshmoylova — COMMENTED** [review]
@henrikt-ma I noticed that you made the same change in https://github.com/modelica/ModelicaSpecification/pull/2882/commits/633b9d843b42f6b3052f7d4907674e3fe3f87dfc Do we need to have a separate fix for just that?

**Review by HansOlsson — APPROVED** [review]
Ok.

**Comment by HansOlsson** [comment]
> Ok.

Except for the conflict.

**Comment by henrikt-ma** [comment]
> @henrikt-ma I noticed that you made the same change in [633b9d8](https://github.com/modelica/ModelicaSpecification/commit/633b9d843b42f6b3052f7d4907674e3fe3f87dfc) Do we need to have a separate fix for just that?

Yes, it would have made sense to remove the change in the other branch.  I simply forgot when realizing that the plural 's' fix should really be a separate PR.  (Not mixing unrelated things in the same PR was not the only reason for splitting: the other was that I wanted to learn the workflow of making these tiny changes using only online editing on my fork.)

**Comment by henrikt-ma** [comment]
After resolving the conflict, there's nothing left to merge.  Closing.

**Pull request closed without merging**
