### PR TITLE
Mcp/0032

### PR DESCRIPTION
**Pull request by christoff-buerger**
Added things shown and discussed at the 100th Modelica Design Meeting.

### CODE REVIEW

**Comment by dietmarw** [comment]
You should rebase this on master first. Just to make it a clean PR. If unsure how I can do that.

**Comment by dietmarw** [comment]
@christoff-buerger ping

**Comment by christoff-buerger** [comment]
> 
> 
> @christoff-buerger ping

For some stupid reasons I cannot rebase in the GitHib GUI, although it works fine in my fork. I will close the pull request and reopen it based on my rebased branch of my fork.

**Comment by sjoelund** [comment]
Why not rebase in your fork and `push --force`?

**Comment by christoff-buerger** [comment]
> 
> 
> Why not rebase in your fork and `push --force`?

See my above updated comment.

**Comment by sjoelund** [comment]
You just `git fetch upstream` or whatever remote you have for this repository.

```
git remote add upstream git@github.com:modelica/ModelicaSpecification
git fetch upstream
git checkout MCP/0032
git rebase -i upstream/master
git push --force
```

**Comment by christoff-buerger** [comment]
> 
> 
> You just `git fetch upstream` or whatever remote you have for this repository.
> 
> ```
> git remote add upstream git@github.com:modelica/ModelicaSpecification
> git fetch upstream
> git checkout MCP/0032
> git rebase -i upstream/master
> git push --force
> ```

Please check how I integrated the recent MCP changes via two ordinary pull-requests and conflict-free merges; the first pull-request to update the official/this repositories' MCP branch with its own master and the second to bring in the recent changes of the MCP branch from my fork. The first pull-request is a nobrainer, the second clearly encapsulates the actual MCP changes. I think this is the way to go and your proposal with `git push --force` completely misses the point here; a `--force` should **never** be required for a MCP still in development (NOT master) and just updated from contributors personal forks.

Regarding rebase: This is not helping since what we want is a rebase between master and branch of **this** repository (it does not help to rebase my updated fork when the MCP branch in this repository is outdated). To update **this** repositories' MCP branch with **its** master can be done by a simple pull request; then the following pull request from a fork to the MCP branch of this repository will nicely encapsulate the actual MCP changes only.

That is what @dietmarw wants (if I understood right); not funny `--force` pushes.

**Comment by sjoelund** [comment]
If what you want is to update the repository without a push --force, what you want is a merge (not a rebase):
```
git remote add upstream git@github.com:modelica/ModelicaSpecification
git fetch upstream
git checkout MCP/0032
git rebase -i upstream/MCP/0032 # Forces your local branch to be up to date with the MCP upstream
git push --force # Your local branch might have changed the history due to the rebase
git merge upstream/master # Updates your local branch to the master
git push
# When merging in github UI, the upstream branch is never force pushed
```

**Pull request closed without merging**
