### PR TITLE
Call the preferredView string the 'view'

### PR DESCRIPTION
**Pull request by henrikt-ma**
Extracted from #3067 according to comment: https://github.com/modelica/ModelicaSpecification/pull/3067#discussion_r766461221

### CODE REVIEW

**Comment by HansOlsson** [comment]
Alternatively we could use "view" instead of "layer" from the old text; as both "diagram view" and "text view" have been used.
The problem is info/documentation, but that could be worked around like below.

`The $\mathit{view}$ is a \lstinline!String! literal where \lstinline!"info"! means viewing the class documentation (or information), \lstinline!"diagram"! means  diagram view, \lstinline!"icon" means icon view, and \lstinline!"text"! means Modelica text view.`

**Comment by henrikt-ma** [comment]
> Alternatively we could use "view" instead of "layer" from the old text; as both "diagram view" and "text view" have been used.
> The problem is info/documentation, but that could be worked around like below.

Yeah, I'm mainly trying to avoid too much repetition, but if you feel strongly about more _view_ and _text_ in the sentence I'll just change.

**Comment by HansOlsson** [comment]
> Yeah, I'm mainly trying to avoid too much repetition, but if you feel strongly about more _view_ and _text_ in the sentence I'll just change.

To me that repetition provides a sort of consistency.

**Comment by henrikt-ma** [comment]
> > Yeah, I'm mainly trying to avoid too much repetition, but if you feel strongly about more _view_ and _text_ in the sentence I'll just change.
> 
> To me that repetition provides a sort of consistency.

OK, now at least two of them repeat _view_, and all of them repeat the string one way or another in the explanation.

**Review by HansOlsson — APPROVED** [review]
Looks good.

**Pull request merged**
